phate/jlm

Makefile, Makefile.sub, jlm-opt/Makefile.sub, jlm-print/Makefile.sub, libjlc/Makefile.sub, libjlm/Makefile.sub, tests/Makefile.sub
Hopefully addresses all previous comments
=> Makefile updates

.github/workflows/tests.yml
The polybench test is now using the more efficient check,
which uses md5 sums to verify the results.
=> CI: Changed polybench test to use check

.github/workflows/tests.yml, tests/Makefile.sub
Added valgrind to continuous integration.
Should probably wait with merging until the valgrind check passes.
=> CI: Added valgrind check

libjlm/src/opt/inlining.cpp, tests/libjlm/opt/test-inlining.cpp
It could have happened that we inlined functions that were given
as arguments to function calls.
=> libjlm/iln: fix bug in inliner

.github/workflows/tests.yml
The llvm-test-suite CI should now work
=> CI: Added llvm-test-suite

libjlm/include/jlm/ir/operators/operators.hpp, libjlm/src/backend/llvm/jlm2llvm/instruction.cpp, libjlm/src/frontend/llvm/llvm2jlm/instruction.cpp, libjlm/src/ir/operators/operators.cpp, tests/libjlm/ir/operators/Makefile.sub, tests/libjlm/ir/operators/test-ConstantFP.cpp
1. Rename fpconstant_op to ConstantFP
2. Fix implementation of equality operator of ConstantFP operator
=> Fix implementation of ConstantFP

libjlm/include/jlm/backend/llvm/jlm2llvm/type.hpp, libjlm/include/jlm/ir/operators/operators.hpp, libjlm/include/jlm/ir/types.hpp, libjlm/include/jlm/opt/alias-analyses/PointsToGraph.hpp, libjlm/include/jlm/opt/alias-analyses/Steensgaard.hpp, libjlm/src/backend/llvm/jlm2llvm/type.cpp, libjlm/src/frontend/llvm/LlvmTypeConversion.cpp, libjlm/src/ir/types.cpp, libjlm/src/opt/alias-analyses/Steensgaard.cpp, tests/TestRvsdgs.cpp, tests/TestRvsdgs.hpp, tests/libjlm/backend/llvm/jlm-llvm/test-type-conversion.cpp, tests/libjlm/opt/alias-analyses/TestSteensgaard.cpp
1. Some clean up
2. Overhauls StructType
3. Fixes bug in points-to graph construction of Steensgaard analysis
Best to be reviewed commit by commit.
=> Fix bug in PointsTo graph construction of Steensgaard analysis

.github/workflows/hls.yml, jlm-hls/Makefile.sub, jlm/hls/backend/rhls2firrtl/base-hls.cpp, jlm/hls/backend/rhls2firrtl/firrtl-hls.cpp, jlm/hls/backend/rhls2firrtl/mlirgen.cpp, jlm/hls/backend/rhls2firrtl/mlirgen.hpp
It would be beneficial to have the latest version of the backend as part of master
=> libjlm/backend/hls: Updated CIRCT version

jlm/tooling/Command.cpp, jlm/tooling/Command.hpp, jlm/tooling/CommandGraph.cpp, jlm/tooling/CommandGraph.hpp, jlm/tooling/CommandGraphGenerator.cpp, jlm/tooling/CommandGraphGenerator.hpp, jlm/tooling/CommandLine.cpp, jlm/tooling/CommandLine.hpp, jlm/tooling/Makefile.sub, tests/jlm/tooling/TestJlcCommandGraphGenerator.cpp, tests/jlm/tooling/TestJlcCommandLineParser.cpp, tools/jhls/jhls.cpp, tools/jlc/jlc.cpp, tools/jlm-hls/jlm-hls.cpp, tools/jlm-opt/jlm-opt.cpp
Introduces the jlm::tooling namespace for the tooling library.
=> Create jlm::tooling namespace

jlm/llvm/opt/alias-analyses/PointsToGraph.hpp
=> Add Is() method to PointsToGraph::Node class

jlm/rvsdg/traverser.hpp
=> Add missing forward declarations and headers to jlm/rvsdg/tracker.hpp

jlm/util/HashSet.hpp, tests/jlm/util/TestHashSet.cpp
=> Add IntersectWith() method to util::HashSet class

jlm/llvm/opt/alias-analyses/RegionAwareMemoryNodeProvider.cpp, jlm/llvm/opt/alias-analyses/RegionAwareMemoryNodeProvider.hpp
=> Move RegionAwareMemoryNodeProvider class constructor to cpp file

jlm/llvm/opt/alias-analyses/EliminatedMemoryNodeProvider.hpp
=> Add EliminatedMemoryNodeProvider class

.github/actions/InstallLlvmDependencies/action.yml, .github/workflows/hls.yml, .github/workflows/tests.yml
Creates a composite action for installing all the required LLVM dependencies and uses it in the various workflows.
=> Create LLVM composite action

jlm/hls/Makefile.sub, jlm/hls/backend/rvsdg2rhls/ThetaConversion.cpp, jlm/hls/backend/rvsdg2rhls/ThetaConversion.hpp, jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.cpp, jlm/hls/backend/rvsdg2rhls/theta-conv.cpp, jlm/hls/backend/rvsdg2rhls/theta-conv.hpp, tests/jlm/hls/backend/rvsdg2rhls/TestTheta.cpp
I have quite some problems with refactoring the HLS code. Start to clean it up such that I can familiarize myself better with the code and gain a better starting position for refactoring. This PR overhauls the theta conversion pass.
=> Clean up HLS theta conversion

jlm/hls/Makefile.sub, jlm/hls/backend/rvsdg2rhls/GammaConversion.cpp, jlm/hls/backend/rvsdg2rhls/GammaConversion.hpp, jlm/hls/backend/rvsdg2rhls/gamma-conv.cpp, jlm/hls/backend/rvsdg2rhls/gamma-conv.hpp, jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.cpp, tests/jlm/hls/backend/rvsdg2rhls/TestGamma.cpp
This PR overhauls the HLS gamma conversion pass to make it more amenable for refactoring.
=> Clean up HLS gamma conversion

.github/actions/BuildCirct/action.yml, .github/actions/InstallLlvmDependencies/action.yml, .github/workflows/hls.yml
This simplifies the HLS test flow.
=> CI: Building CIRCT using an action

jlm/llvm/opt/InvariantValueRedirection.cpp, jlm/llvm/opt/InvariantValueRedirection.hpp
=> Move InvariantValueRedirection statistics class into InvariantValueRedirection namespace

jlm/llvm/opt/alias-analyses/Steensgaard.cpp, jlm/llvm/opt/alias-analyses/Steensgaard.hpp
This PR only performs structural changes to the Steensgaard analysis. It should not change anything semantically. It is meant as a prerequisite before I start to tackle actual issues in the analysis.
=> Clean up Steensgaard

doxygen.conf
This PR enables the documentation generation for private and static members.
=> Enable documentation generation for private and static members

.github/actions/InstallLlvmDependencies/action.yml, .github/workflows/tests.yml
=> Added llvm-lit to InstallLlvmDependencies in CI

jlm/util/Makefile.sub, jlm/util/time.hpp, tests/jlm/util/TestTimer.cpp
=> Add resuming and resetting to util::timer, and a test

jlm/llvm/backend/rvsdg2jlm/rvsdg2jlm.cpp, jlm/llvm/frontend/InterProceduralGraphConversion.cpp, jlm/llvm/opt/DeadNodeElimination.cpp, jlm/llvm/opt/InvariantValueRedirection.cpp, jlm/llvm/opt/OptimizationSequence.cpp, jlm/llvm/opt/alias-analyses/AgnosticMemoryNodeProvider.hpp, jlm/llvm/opt/alias-analyses/MemoryStateEncoder.cpp, jlm/llvm/opt/alias-analyses/RegionAwareMemoryNodeProvider.hpp, jlm/llvm/opt/alias-analyses/Steensgaard.cpp, jlm/llvm/opt/cne.cpp, jlm/llvm/opt/inlining.cpp, jlm/llvm/opt/inversion.cpp, jlm/llvm/opt/pull.cpp, jlm/llvm/opt/push.cpp, jlm/llvm/opt/reduction.cpp, jlm/llvm/opt/unroll.cpp, jlm/util/Statistics.hpp
This PR refactors statistics classes to use the new Statistics class interface.
=> Convert statistics classes to use new interface

jlm/hls/Makefile.sub, jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.cpp, jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.hpp, tools/jlm-hls/jlm-hls.cpp
Class name changed from MlirGen to RhlsToFirrtlConverter
Two classes have been reduced to a single class
=> Refactored the FIRRTL generation

.github/actions/BuildJlm/action.yml, .github/actions/InstallLlvmDependencies/action.yml, .github/workflows/Doxygen.yml, .github/workflows/hls.yml, .github/workflows/tests.yml
This PR adds a composite action for building jlm. This PR lays the foundation for the restructuring of our CI tests.
=> [Andersen] Add and utilize jlm build composite action

jlm/util/Statistics.cpp, jlm/util/Statistics.hpp
This is the last PR in series of PRs that refactored the Statistics class serialization.
The other PRs are #384 and #382. Closes #361.
=> Clean up serialization interface of Statistics class

scripts/build-mlir.sh
The mlir-rvsdg repository has been updated to enable building the RVSDG Dialect at a user specified location, which is needed for this script to work.
=> Bumped mlir-rvsdg repository

jlm/hls/backend/rvsdg2rhls/add-prints.cpp, jlm/llvm/backend/jlm2llvm/instruction.cpp, jlm/llvm/backend/jlm2llvm/jlm2llvm.cpp, jlm/llvm/backend/jlm2llvm/type.cpp, jlm/llvm/frontend/LlvmConversionContext.hpp, jlm/llvm/frontend/LlvmInstructionConversion.cpp, jlm/llvm/frontend/LlvmModuleConversion.cpp, jlm/llvm/frontend/LlvmTypeConversion.cpp, jlm/llvm/ir/operators/call.hpp, jlm/llvm/ir/operators/operators.cpp, jlm/llvm/ir/operators/operators.hpp, jlm/llvm/ir/types.cpp, jlm/llvm/ir/types.hpp, jlm/llvm/opt/InvariantValueRedirection.cpp, jlm/mlir/backend/JlmToMlirConverter.cpp, jlm/mlir/frontend/MlirToJlmConverter.cpp, tests/TestRvsdgs.cpp, tests/jlm/llvm/frontend/llvm/test-function-call.cpp, tests/jlm/llvm/ir/operators/TestCall.cpp, tests/jlm/llvm/ir/operators/TestLambda.cpp, tests/jlm/llvm/ir/operators/TestPhi.cpp, tests/jlm/llvm/opt/TestInvariantValueRedirection.cpp, tests/jlm/llvm/opt/alias-analyses/TestMemoryStateEncoder.cpp, tests/jlm/llvm/opt/test-inlining.cpp, tests/jlm/mlir/backend/TestJlmToMlirConverter.cpp, tests/jlm/mlir/frontend/TestMlirToJlmConverter.cpp
The loop state was a quick idea that turned out to be a dead end. By now it also became a burden. Let's remove it.
=> Remove loop state

jlm/llvm/ir/operators/load.cpp, tests/jlm/llvm/ir/operators/TestLoad.cpp
It failed to take the loaded type into account.
=> Fix equality operator of LoadOperation class

jlm/llvm/ir/operators/store.cpp, tests/jlm/llvm/ir/operators/TestStore.cpp
It failed to take stored type into account.
=> Fix equality operator of StoreOperation class

jlm/llvm/ir/operators/Load.cpp, jlm/llvm/ir/operators/Load.hpp, jlm/llvm/opt/alias-analyses/Andersen.cpp, jlm/llvm/opt/alias-analyses/MemoryStateEncoder.cpp, jlm/llvm/opt/alias-analyses/RegionAwareMemoryNodeProvider.cpp, jlm/llvm/opt/alias-analyses/Steensgaard.cpp
1. Introduces an abstract base class for load operations
2. Introduces an abstract base class for load nodes
3. Factors out common functionality for the load classes
=> Introduce abstract base classes for load operations and nodes

jlm/llvm/ir/operators/Load.cpp, jlm/llvm/ir/operators/Store.cpp, jlm/llvm/ir/operators/Store.hpp, jlm/llvm/opt/alias-analyses/Andersen.cpp, jlm/llvm/opt/alias-analyses/MemoryStateEncoder.cpp, jlm/llvm/opt/alias-analyses/RegionAwareMemoryNodeProvider.cpp, jlm/llvm/opt/alias-analyses/Steensgaard.cpp, tests/jlm/llvm/ir/operators/StoreTests.cpp
1. Introduces an abstract base class for store operations
2. Introduces an abstract base class for store nodes
3. Factors out common functionality for the store classes
=> Introduce abstract base classes for store operations and nodes

jlm/llvm/opt/alias-analyses/MemoryStateEncoder.cpp, jlm/llvm/opt/alias-analyses/MemoryStateEncoder.hpp
This PR overhauls the Memory state encoder in anticipation of the upcoming changes necessary for volatile memory accesses.
=> Overhaul MemoryStateEncoder.[ch]pp

jlm/llvm/opt/alias-analyses/Andersen.cpp, jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp, jlm/llvm/opt/alias-analyses/PointerObjectSet.hpp, jlm/util/GraphWriter.cpp, jlm/util/GraphWriter.hpp, tests/jlm/util/TestGraphWriter.cpp
While debugging other things, I caved and put together a little web-app to render the Graphviz output, where I can click the nodes, ports and edges to look at their attributes, and highlight related elements. It is lacking features, and doesn't look good (highlight colors are extremely arbitrary), but it did help me debug :)
Note that the webapp should be able to render any Graphviz, not just output from the `GraphWriter`. The utility of the tool is of course greater when nodes and edges have non-standard attributes.
This PR gives nodes a white fill instead of being transparent, making them easier to click (can click anywhere instead of on text or border). The rest of the PR is just cleanup of the code used to dump the PointerObjectSet subset graph.
If you want to try the webapp, it's …
=> Improve dot output slightly, to make ports easier to click in my tool

jlm/hls/backend/rvsdg2rhls/mem-conv.cpp, jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.cpp
Removed statements that have been used for debugging.
=> Removed dumping RVSDG as XML to file

jlm/llvm/opt/alias-analyses/Andersen.cpp, jlm/llvm/opt/alias-analyses/Andersen.hpp, jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp, jlm/llvm/opt/alias-analyses/PointerObjectSet.hpp, tests/jlm/llvm/opt/alias-analyses/TestAndersen.cpp, tests/jlm/llvm/opt/alias-analyses/TestPointerObjectSet.cpp
Adds Hybrid Cycle Detection from Hardekopf 2007. The implementation is quite simple, but requires some extra info to be kept from the Offline Variable Substitution.
=> [AndersenAgnostic] Add hybrid cycle detection to Andersen

README.md
We forgot to bump the LLVM version to 18.
=> Change LLVM version in README.md

jlm/llvm/opt/OptimizationSequence.hpp, jlm/tooling/CommandLine.cpp, jlm/tooling/CommandLine.hpp, tests/jlm/tooling/TestJlmOptCommandLineParser.cpp
We need them going forward if we want to adjust the optimizations from the command line.
=> Add support for dynamically configurable optimizations

jlm/rvsdg/theta.cpp, jlm/rvsdg/theta.hpp
Add class for representing the predicate result of a theta node.
=> Add ThetaPredicateResult class

.github/workflows/CheckHeaders.yml, jlm/llvm/Makefile.sub
=> Add header check to CI

jlm/llvm/opt/push.cpp
=> Avoid hoisting loads out of gammas

jlm/rvsdg/node.cpp
Operations that have side effect should not go into JLM_ASSERT.
Otherwise, they will not be executed in release builds.
=> unbreak release build: no side effects in JLM_ASSERT

jlm/llvm/ir/RvsdgModule.hpp, jlm/rvsdg/RvsdgModule.hpp
This prepares for refactoring the transformation classes and promoting them to the rvsdg namespace.
=> Promote source file path to RvsdgModule base class

jlm/llvm/backend/RvsdgToIpGraphConverter.cpp, jlm/llvm/backend/RvsdgToIpGraphConverter.hpp
Cleans up the RvsdgToIpGraphConverter class.
=> Clean up rvsdg to ip graph converter

jlm/mlir/backend/JlmToMlirConverter.cpp, jlm/mlir/frontend/MlirToJlmConverter.cpp, scripts/build-mlir.sh, tests/jlm/mlir/TestJlmToMlirToJlm.cpp
Depends https://github.com/EECS-NTNU/mlir_rvsdg/pull/7
=> Free conversion

jlm/hls/Makefile.sub, jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.cpp, jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.hpp, jlm/hls/backend/rhls2firrtl/base-hls.cpp, jlm/hls/backend/rhls2firrtl/base-hls.hpp, jlm/hls/backend/rhls2firrtl/verilator-harness-hls.cpp, jlm/hls/backend/rvsdg2rhls/add-prints.cpp, jlm/hls/backend/rvsdg2rhls/add-prints.hpp, jlm/hls/backend/rvsdg2rhls/alloca-conv.cpp, jlm/hls/backend/rvsdg2rhls/hls-function-util.cpp, jlm/hls/backend/rvsdg2rhls/hls-function-util.hpp, jlm/hls/backend/rvsdg2rhls/instrument-ref.cpp, jlm/hls/backend/rvsdg2rhls/mem-conv.cpp, jlm/hls/backend/rvsdg2rhls/mem-conv.hpp, jlm/hls/backend/rvsdg2rhls/mem-queue.cpp, jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.cpp, jlm/hls/ir/hls.cpp, jlm/hls/ir/hls.hpp
Adds support for variable width memory ports, support for floating point operations, and a reduced/simplified mem-conv transformation.
=> Supporting functionality for decoupled access execute

jlm/llvm/opt/alias-analyses/AgnosticModRefSummarizer.cpp, jlm/llvm/opt/alias-analyses/AgnosticModRefSummarizer.hpp, jlm/llvm/opt/alias-analyses/EliminatedModRefSummarizer.hpp, jlm/llvm/opt/alias-analyses/MemoryStateEncoder.cpp, jlm/llvm/opt/alias-analyses/ModRefSummarizer.hpp, jlm/llvm/opt/alias-analyses/Optimization.cpp, jlm/llvm/opt/alias-analyses/Optimization.hpp, jlm/llvm/opt/alias-analyses/RegionAwareModRefSummarizer.cpp, jlm/llvm/opt/alias-analyses/RegionAwareModRefSummarizer.hpp, jlm/llvm/opt/alias-analyses/TopDownModRefEliminator.cpp, jlm/llvm/opt/alias-analyses/TopDownModRefEliminator.hpp, jlm/tooling/CommandLine.cpp, jlm/util/Statistics.cpp, jlm/util/Statistics.hpp, tests/jlm/llvm/opt/alias-analyses/AgnosticModRefSummarizerTests.cpp, tests/jlm/llvm/opt/alias-analyses/RegionAwareModRefSummarizerTests.cpp
This just cleans up the rest of the code after all the renaming.
=> Rename provider/provisioning to summarizer and mod/ref summary

jlm/llvm/Makefile.sub, jlm/llvm/backend/RvsdgToIpGraphConverter.cpp, jlm/llvm/backend/RvsdgToIpGraphConverter.hpp, jlm/llvm/opt/IfConversion.cpp, jlm/llvm/opt/IfConversion.hpp, jlm/tooling/Command.cpp, jlm/tooling/CommandLine.cpp, jlm/tooling/CommandLine.hpp, jlm/util/Statistics.cpp, jlm/util/Statistics.hpp, tests/jlm/llvm/backend/RvsdgToIpGraphConverterTests.cpp, tests/jlm/llvm/opt/IfConversionTests.cpp
This PR moves the if-conversion from the RvsdgToIpGraphConverter into its own RVSDG transformation.
=> Add IfConversion transformation

jlm/hls/Makefile.sub, jlm/hls/backend/rhls2firrtl/VerilatorHarnessAxi.cpp, jlm/hls/backend/rhls2firrtl/VerilatorHarnessAxi.hpp, jlm/hls/backend/rhls2firrtl/verilator-harness-hls.hpp
This harness is used when performing synthesis
=> Adds Verilator AXI harness

jlm/llvm/opt/DeadNodeElimination.cpp
Unifies the output handling in DNE's mark phase. This PR is in preparation for refactoring DNE such that it is possible to inject handlers for different kind of nodes. This allows DNE to become extensible for different node types and ultimately would enable us to unify the two DNE transformations in the code base (LLVM and HLS).
=> Unify output handling in DNE mark phase

jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.cpp, jlm/hls/backend/rhls2firrtl/dot-hls.cpp, jlm/hls/ir/hls.hpp
=> HLS: Remove unused merge_op operation

jlm/rvsdg/node.cpp, jlm/rvsdg/node.hpp, jlm/rvsdg/region.cpp, jlm/rvsdg/region.hpp
Performing the same change as for the Input class in #1060.
=> Add owner attribute to Output class

jlm/llvm/opt/cne.cpp, tests/jlm/llvm/opt/test-cne.cpp
1. It could be that we check congruence for values that are the arguments from different theta nodes. This caused an JLM_ASSERT() to be thrown in the original code. Let's ensure that we handle this case gracefully.
2. Overhaul the CNE congruence check to reflect the latest API changes.
=> Fix Common Node Elimination

jlm/mlir/backend/JlmToMlirConverter.cpp, jlm/mlir/frontend/MlirToJlmConverter.cpp, scripts/build-mlir.sh
Also fixes an incorrect comment
=> Add coversion of MemoryStateJoin to/from MLIR

jlm/hls/backend/rvsdg2rhls/add-prints.cpp, jlm/hls/backend/rvsdg2rhls/add-prints.hpp, jlm/hls/backend/rvsdg2rhls/instrument-ref.cpp, jlm/hls/backend/rvsdg2rhls/mem-sep.cpp, jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.cpp, jlm/llvm/opt/inlining.cpp, jlm/rvsdg/node.cpp, jlm/rvsdg/node.hpp, tests/jlm/rvsdg/OutputTests.cpp
Adds a general RouteToRegion() function and replaces all usages of the old instances with the new function.
=> Add RouteToRegion() function

jlm/llvm/opt/alias-analyses/Andersen.cpp, jlm/llvm/opt/alias-analyses/Steensgaard.cpp, jlm/llvm/opt/cne.cpp
Pattern-match on nodes and operation classes of simple nodes for Andersen/Steensgaard alias analysis as well as common node elimination.
=> Use pattern matching and correct op dispatch
