- Makefile
The setup depend on Makefile.sub from the jive submodules but it
does not exist until 'make submodule' has been done so the include
needs to be guarded
> Added checks if submodules been initiated

- Makefile
release is a simple alias for jlm-release while debug calls
jlm-debug followed by check.
clean has been modified to not call jive-clean and instead
deep-clean has been added, which calls both jlm-clean and
jive-clean.
> make: Added release, debug and deep-clean as targets

- libjlm/include/jlm/common.hpp
- libjlm/include/jlm/ir/ipgraph.hpp
- libjlm/include/jlm/ir/operators/call.hpp
- libjlm/include/jlm/ir/operators/delta.hpp
- libjlm/include/jlm/ir/operators/load.hpp
- libjlm/include/jlm/ir/operators/operators.hpp
- libjlm/include/jlm/ir/operators/store.hpp
- libjlm/include/jlm/ir/tac.hpp
- libjlm/include/jlm/ir/types.hpp
- libjlm/include/jlm/ir/variable.hpp
- libjlm/include/jlm/util/stats.hpp
- libjlm/src/ir/operators/call.cpp
- libjlm/src/llvm2jlm/instruction.cpp
These changes address most warnings from clang but maybe should be solved differently. So this is to start the discussion on how the warnings should be addressed.
> LLVM warnings

- libjlc/include/jlc/cmdline.hpp
- libjlc/include/jlc/command.hpp
- libjlc/src/cmdline.cpp
- libjlc/src/command.cpp
It's now possible to specify jlm-opt optimizations using -J.
There's also a default set of optimization specified if -J is not
used.
> jlc: Added the option to specify jlm-opt optimization -J

- libjlc/include/jlc/cmdline.hpp
- libjlc/include/jlc/command.hpp
- libjlc/src/cmdline.cpp
- libjlc/src/command.cpp
Must have deleted a line by mistake when adding the previous changes as to commits.
The opts.jlmopts was never set in cmdline.cpp so didn't matter if -J was specified for jlc.
> Jlc opt flags

- tests/Makefile.sub
Faulty checks used to end with a quiet exit and has been changed
to exit with none zero exit code. This behavior fits better with
continuous integration.
> make: Added 'exit 1' to c and unit tests

- Makefile
ar was using clqv as arguments, which cause an error when trying
to create libjlm.a on Ubuntu 21.10
Error message
ar: libdeps specified more than once
The l argument has been removed, i.e., ar is now usig cqv.
The change has also been tested to work with Ubuntu 20.04.3
> make: Removed the 'l' option for the ar command

- tests/Makefile.sub
- tests/test-jlc.sh
'make jlm-check' can now be run in other directories than the
JLM_ROOT
> tests: Added JLM_ROOT to paths

- Makefile.sub
- jlm-hls/Makefile.sub
- jlm-hls/include/jlm-hls/cmdline.hpp
- jlm-hls/src/cmdline.cpp
- jlm-hls/src/jlm-hls.cpp
- libjlm/include/jlm/backend/hls/rhls2firrtl/base-hls.hpp
- libjlm/include/jlm/backend/hls/rhls2firrtl/mlirgen.hpp
- libjlm/src/backend/hls/rhls2firrtl/mlirgen.cpp
The tool has support extracting specified function for synthesis.
Inlining is performed such that the extracted function does not
contain any function calls. Thus, the LLVM IR used as input has
to contain all functions that's called by the extracted function.
The tool also has support for generating FIRRTL or a DOT graph of
the provided input function after the RVSDG has been created and
lowered to RHLS.
> jlm-hls: Tool for interacting with the libljm HLS backend

- .github/workflows/tests.yml
The CI now also runs the hls-test-suite with the new Ubuntu 22.04
runner.
> CI: Added hls-test-suite

- libjlm/include/jlm/util/time.hpp
The result from the high_resolution_clock was stored as a
system_clock variable, which causes an error when compiling
on Mac.
> libjlm: Changed variable to high_resolution_clock

- libjlm/src/ir/operators/lambda.cpp
Attributes of fctarguments are currently discarded when a lambda is copied.
> libjlm/ir: Copy argument attributes in lambda copy

- libjlm/include/jlm/tooling/Command.hpp
- libjlm/src/tooling/CommandGraphGenerator.cpp
- tests/libjlm/tooling/TestJlcCommandGraphGenerator.cpp
- tests/libjlm/tooling/TestJlcCommandLineParser.cpp
jlc accepted the -J argument but didn't pass on the optimizations to jlm-opt
> libjlm/tooling: Added missing support for -J in jlc

- libjive/include/jive/rvsdg/traverser.hpp
- libjlm/src/opt/alias-analyses/MemoryStateEncoder.cpp
- tests/libjlm/opt/alias-analyses/AliasAnalysesTests.cpp
- tests/libjlm/opt/alias-analyses/AliasAnalysesTests.hpp
- tests/libjlm/opt/alias-analyses/TestMemoryStateEncoder.cpp
We had a bug in the memory state encoder where traverser visited newly created nodes. This should never happen in the memory state encoder. The PR contains the following:
1. Added documentation to topdown_traverser class
2. Added DeltaTest3 alias analysis test
3. Fixed bug in memory state encoder
> Fix wrong traversal in memory state encoder

- libjlm/src/opt/alias-analyses/Steensgaard.cpp
- tests/TestRvsdgs.cpp
- tests/TestRvsdgs.hpp
- tests/libjlm/opt/alias-analyses/TestSteensgaard.cpp
We got a segmentation fault when analyzing the pointer arguments of external calls with the Steensgaard alias analysis. This PR adds a unit test exposing the problem and fixes it.
> Steensgaard bug

- libjlm/include/jlm/ir/ipgraph.hpp
- libjlm/include/jlm/ir/operators/alloca.hpp
- libjlm/include/jlm/ir/operators/load.hpp
- libjlm/include/jlm/ir/operators/operators.hpp
- libjlm/include/jlm/ir/operators/store.hpp
- libjlm/src/frontend/llvm/LlvmInstructionConversion.cpp
- libjlm/src/ir/operators/load.cpp
- libjlm/src/opt/alias-analyses/MemoryStateEncoder.cpp
- tests/TestRvsdgs.cpp
- tests/libjlm/ir/operators/TestCall.cpp
- tests/libjlm/opt/TestLoadMuxReduction.cpp
- tests/libjlm/test-load.cpp
The biggest change when porting to LLVM 15 is the transition to [opaque pointers](https://releases.llvm.org/14.0.0/docs/OpaquePointers.html). This means that we have to get rid off the element type in the PointerType class. A prerequisite for this is to eliminate all usages of the GetElementType() method, which in turn means that we have to add types explicitly to certain operations.
This PR removes some usages of the GetElementType() method of the PointerType class. These were the low hanging fruits. The other usages will be removed in a later PR.
> Porting jlm to LLLVM 15 part 1

- libjlm/src/backend/hls/rhls2firrtl/verilator-harness-hls.cpp
LLVM-15 use opaque pointers, so to avoid using GetElementType() we simply use void*, as the function is external and correctly links anyway.
> [backend][hls] Removed use of GetElementType()

- .github/workflows/tests.yml
We currently run the tests twice: once a PR is created and once after the PR is merged to master. This is wasteful and we can avoid the second test run.
> Avoid test runs for pushing to master

- jlm/hls/backend/rhls2firrtl/mlirgen.cpp
Missed update in previous commit.
> hls/backend: Removed jive namespace from strfmt

- .github/workflows/hls.yml
This should eliminate CIRCT rebuilds when jobs fail
> CI: Moved CIRCT build to its own job in HLS workflow

- jlm/tooling/CommandGraphGenerator.cpp
- jlm/tooling/CommandLine.cpp
- jlm/tooling/CommandLine.hpp
- tests/jlm/tooling/Makefile.sub
- tests/jlm/tooling/TestJlcCommandGraphGenerator.cpp
- tests/jlm/tooling/TestJlcCommandLineParser.cpp
- tests/jlm/tooling/TestJlmOptCommandLineParser.cpp
- tools/jlc/jlc.cpp
This fixes a jlc command line parsing bug where an invalid jlm-opt optimization did not lead to a command line parsing error.
> Fix jlc command line parsing bug

- jlm/tooling/Command.cpp
- jlm/tooling/Command.hpp
- jlm/tooling/CommandGraphGenerator.cpp
- jlm/tooling/CommandLine.cpp
- jlm/tooling/CommandLine.hpp
- jlm/util/Statistics.hpp
- tests/jlm/tooling/TestJlcCommandGraphGenerator.cpp
- tools/jlm-opt/jlm-opt.cpp
The JlmOptCommand class represents the jlm-opt command line tool. This PR moves the entire logic of the jlm-opt command line tool from the jlm-opt.c file into the JlmOptCommand class. This permits for better testing in the future and cleans up quite a few code smells. Specifically, this PR makes the following changes:
1. It privatizes all attributes of the JlmOptCommandLineOptions class.
2. Establishes the JlmOptCommandLineOptions::OptimizationIds as the sole truth for jlm-opt optimizations.
3. Ensures that the jlm-opt optimizations performed under the hood by jlc are set in the command line parser and not later in the pipeline.
4. Moves the jlm-opt logic into the JlmOptCommand class
> Move jlm-opt logic into JlmOptCommand class

- jlm/tooling/CommandLine.cpp
- jlm/tooling/CommandLine.hpp
- tests/jlm/tooling/TestJlcCommandGraphGenerator.cpp
- tests/jlm/tooling/TestJlcCommandLineParser.cpp
1. Adds more descriptive optimization flags to jlm-opt
3. Marks the non-descriptive optimization flags as deprecated
4. Replaces all internal usages of the non-descriptive optimizations with the corresponding descriptive optimization
The non-descriptive optimization flags will be removed in a future PR after all external usages have been converted to the descriptive optimization flags.
> Add descriptive optimization flags to jlm-opt

- jlm/tooling/CommandLine.cpp
This PR stores the runtime string description of the `-s` option in a `std::string` on stack,
which keeps the string alive long enough for the `StringRef` passed to `cl::desc()` to stay valid.
Constructing the string could also be done using `std::stringstream`, the current fix just moves the `+` result to stack frame ownership.
Fixes issue #245
> Fix use-after-free-bug in jlm-opt --help due to implicit StringRef

- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
- jlm/llvm/opt/alias-analyses/Steensgaard.hpp
- jlm/tooling/CommandLine.cpp
- jlm/util/Statistics.hpp
- tests/jlm/llvm/opt/alias-analyses/TestSteensgaard.cpp
Simplifies the Steensgaard alias analysis statistics. The PR makes the following changes:
1. Merge the alias analysis and points-to graph construction statistics into a single statistics
2. Remove the dead steensgaard points-to graph construction statistics option from jlm-opt command line interface
3. Add a simple unit test to ensure the statistics is actually gathered
> Simplify Steensgaard alias analysis statistics

- jlm/tooling/Command.cpp
- jlm/tooling/CommandGraphGenerator.cpp
- jlm/tooling/CommandLine.cpp
- jlm/tooling/CommandLine.hpp
- jlm/util/Statistics.hpp
- tests/jlm/tooling/Makefile.sub
- tests/jlm/tooling/TestJlcCommandGraphGenerator.cpp
- tests/jlm/tooling/TestJlcCommandLineParser.cpp
- tests/jlm/tooling/TestJlmOptCommand.cpp
- tests/jlm/tooling/TestJlmOptCommandLineParser.cpp
Adds support for collecting jlm-opt statistics via jlc. Usage:
`jlc --JlmOptPassStatistics=print-aggregation-time inputFile.c`
It utilizes the same command line arguments for gathering statistics as jlm-opt.
> Add statistics collection support to jlc

- jlm/tooling/Command.cpp
- jlm/tooling/CommandGraphGenerator.cpp
- jlm/tooling/CommandLine.cpp
- jlm/util/Statistics.cpp
- jlm/util/Statistics.hpp
- jlm/util/file.hpp
- tests/jlm/tooling/TestJlmOptCommand.cpp
- tests/jlm/util/TestStatistics.cpp
The single statistics file could lead to problems when compiling in parallel as multiple processes would write to the file. Instead we create a unique statistics file per jlm-opt invocation. This PR does the following:
1. Change the semantics of the -s command line option of jlm-opt from specifying the statistics file to specifying a directory. This directory is where the statistics file will end up in.
2. Ensure that unique statistics files are created per jlm-opt invocation.
> Remove jlm-opt's single statistics file

- jlm/llvm/opt/alias-analyses/AgnosticMemoryNodeProvider.cpp
- jlm/llvm/opt/alias-analyses/AgnosticMemoryNodeProvider.hpp
- jlm/llvm/opt/alias-analyses/MemoryStateEncoder.cpp
- tests/TestRvsdgs.cpp
- tests/jlm/llvm/opt/alias-analyses/TestAgnosticMemoryNodeProvider.cpp
This PR fixes some minor statistics inconveniences:
1. Fixes the statistics tag of the agnostic memory node provider
2. Ensures the source file is collected and printed as part of the agnostic memory node provider statistics
3. Fixes the statistics tag of the memory state encoder
> Minor statistics fixes

- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
- jlm/llvm/opt/alias-analyses/Steensgaard.hpp
This PR cleans up the Steensgaard alias analysis. Specifically, it does the following:
1. Align layout of Steensgaard.hpp and Steensgaard.cpp
2. Move LocationSet class to Steensgaard.cpp
3. Discard the internal state after we are done with the analysis to free up memory
4. Rename some private methods for clarity
5. Move join method from Steensgaard class to LocationSet class
> Clean up Steensgaard alias analysis

- jlm/llvm/opt/alias-analyses/Optimization.cpp
- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
- jlm/llvm/opt/alias-analyses/Steensgaard.hpp
- tests/TestRvsdgs.cpp
- tests/TestRvsdgs.hpp
- tests/jlm/llvm/opt/alias-analyses/TestMemoryStateEncoder.cpp
- tests/jlm/llvm/opt/alias-analyses/TestSteensgaard.cpp
This PR makes does the following:
1. Moves the redirection of the points-to graph unknown memory sources to the Steensgaard alias analysis pass. This avoids code duplication and enables the gathering of statistics.
2. Adds some documentation about this pass.
3. Cleans up the Bits2PtrTest class
4. Cleans up the Steensgaard TestBits2Ptr test
> Move points-to graph unknown memory node sources redirection to Steensgaard alias analysis

- jlm/llvm/opt/alias-analyses/MemoryStateEncoder.cpp
This PR ensures that the internal state is only kept for as long as it is needed in the Encode method instead of for the lifetime of an instance of the class.
> Discard internal state after encoding in MemoryStateEncoder

- jlm/llvm/opt/DeadNodeElimination.cpp
- jlm/llvm/opt/DeadNodeElimination.hpp
This PR cleans up the dead node elimination pass:
1. Ensures that internal state is cleared after pass is finished
2. Follow naming conventions
3. Correct indentation in files
4. Clarify method names
5. Use // for comments
6. Add missing constructors and assignment operators
7. Move Context declaration from DeadNodeElimination.hpp to DeadNodeElimination.cpp
8. Clean up parethesis
9. Use AssertedCasts instead of static_casts
> Clean up DeadNodeElimination

- Makefile
- tests/test-registry.cpp
The order of constructor invocation across translation units is not well defined, though it seems fair to guess that the clang++ and g++ linkers, and maybe even MSVC++ use the same order as the object files on the command line. New incremental linkers and other tools may however not expect those constraints.
This can cause the registration of tests to segfault, when the global map is not ready yet. Putting it behind a function ensures that the constructor is called before use.
Also fixes typos in the definition of the PHONY targets `check-ctets` and `check-utets`.
I could not find any reason for these typos being load bearing in this repo nor in the jlm-eval-suite repo.
If only the latter change is desired, I will of course change the PR.
> Fix possible C++ constructor ordering issue when creating test registry

- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
- jlm/llvm/opt/alias-analyses/Steensgaard.hpp
Add second Analyze() method to Steensgaard class for convenience. It does not take a StatisticsCollector parameter.
> Add Analyze() method to Steensgaard class

- jlm/llvm/ir/operators/Phi.cpp
- jlm/llvm/ir/operators/Phi.hpp
- jlm/llvm/opt/alias-analyses/RegionAwareMemoryNodeProvider.cpp
- jlm/llvm/opt/alias-analyses/RegionAwareMemoryNodeProvider.hpp
This PR moves the ExtractLambdaNodes function from the RegionAwareMemoryNodeProvider class to the Phi::node class. It is a useful little piece of code that could be used somewhere else as well.
> Add ExtractLambdaNodes method to phi::node class

- jlm/llvm/opt/alias-analyses/MemoryNodeEliminator.hpp
The interface for future memory node eliminators. This is going to be used by the upcoming lifetime memory node eliminator.
> Add MemoryNodeEliminator interface

- jlm/llvm/opt/alias-analyses/RegionAwareMemoryNodeProvider.cpp
- jlm/llvm/opt/alias-analyses/RegionAwareMemoryNodeProvider.hpp
- jlm/rvsdg/graph.cpp
- jlm/rvsdg/graph.hpp
The ExtractTailNodes function is a useful little piece of code that will be needed elsewhere. Move it from the RegionAwareMemoryNodeProvider class to the rvsdg::graph class.
> Add ExtractTailNodes method to rvsdg::graph class

- jlm/hls/backend/rvsdg2rhls/add-triggers.cpp
- jlm/hls/backend/rvsdg2rhls/remove-unused-state.cpp
- jlm/hls/backend/rvsdg2rhls/rhls-dne.cpp
- jlm/llvm/opt/DeadNodeElimination.cpp
- jlm/llvm/opt/pull.cpp
- jlm/rvsdg/gamma.hpp
- jlm/rvsdg/node.cpp
- jlm/rvsdg/node.hpp
- jlm/rvsdg/region.cpp
- jlm/rvsdg/region.hpp
- jlm/rvsdg/structural-node.hpp
- tests/jlm/rvsdg/Makefile.sub
- tests/jlm/rvsdg/TestRegion.cpp
- tests/jlm/rvsdg/TestStructuralNode.cpp
- tests/jlm/rvsdg/test-gamma.cpp
- tests/jlm/rvsdg/test-nodes.cpp
- tests/test-operation.hpp
The current interface for removing inputs/outputs from nodes/regions has the following downsides:
1. It exposes the way the inputs/outputs are removed to the caller. The caller needs to know how to iterate through the inputs/outputs while removing (some of) them in order to avoid the invalidation of indices:
```
// iterate backwards to avoid the invalidation of 'n' by RemoveOutput()
for (size_t n = noutputs()-1; n != static_cast<size_t>(-1); n--)
{
RemoveOutput(n);
}
```
This is not great for a public interface.
2. The sweep phase of dead node elimination experiences a performance issue when removing multiple inputs/outputs from structural nodes. The removal of an output/input requires the adjustment of the index of (potentially) all other inputs/outputs. In other words, every time we …
> Add methods for removing multiple inputs and outputs

- jlm/llvm/ir/operators/lambda.cpp
- jlm/llvm/ir/operators/lambda.hpp
- tests/jlm/llvm/ir/operators/TestLambda.cpp
We forgot the case where a function pointer is stored in a global variable, i.e., a delta taking a lambda output. Closes #224.
> Add missing case to call summary computation

- .clang-format
There are two reasons I attempted to make a `.clang-format` file for the project.
First and foremost, I want to free up the time Nico spends correcting my curly bracket placement.
I'm also sometimes a bit unsure how to format certain things.
Secondly, I have started to use the [CLion Nova](https://blog.jetbrains.com/clion/2023/11/clion-nova/) preview, in hopes its RAM usage is more modest and stable than CLion Classic.
Reading their blog, it seems it will be merged into CLion in the future, and my experience so far has been ok.
It is better at informing about unnecessarily precise namespaces, inline and stuff.
Formatting (and completion / indenting as you type) is now done by either ReSharper or clang-format, so instead of mucking about in the ReSharper settings dialog, I thought it would …
> Add an attempt at a .clang-format file

- jlm/llvm/ir/operators/delta.cpp
- jlm/llvm/ir/operators/delta.hpp
- jlm/llvm/opt/DeadNodeElimination.cpp
- jlm/llvm/opt/DeadNodeElimination.hpp
- jlm/rvsdg/node.hpp
- tests/jlm/llvm/ir/operators/test-delta.cpp
- tests/jlm/llvm/opt/TestDeadNodeElimination.cpp
This PR adds an API for delta input removal. It contains the following:
1. Add RemoveDeltaInputsWhere and PruneDeltaInputs method to delta node class
2. These implementation hide nasty implementation details, such as iteration order, from outside the class hierarchy
3. Removes the usage of RemoveInput and RemoveArgument from outside the structural node class hierarchy.
4. Adds a test for delta nodes to the TestDeadNodeElimination.cpp. This node was untested.
The implementation of RemoveDeltaInputsWhere will be simplified further down the road. The implementation details, such as iteration order, will be pushed further up the class hierarchy at a later point in time.
> Add delta input removal methods

- jlm/llvm/ir/operators/lambda.hpp
- jlm/llvm/opt/DeadNodeElimination.cpp
- jlm/rvsdg/node.hpp
- tests/jlm/llvm/ir/operators/TestLambda.cpp
This PR adds an API for lambda input removal. It contains the following:
1. Add RemoveLambdaInputsWhere and PruneLambdaInputs method to lambda node class
2. These implementation hide nasty implementation details, such as iteration order, from outside the class hierarchy
3. Removes the usage of RemoveInput and RemoveArgument from outside the structural node class hierarchy.
The implementation of RemoveLambdaInputsWhere will be simplified further down the road. The implementation details, such as iteration order, will be pushed further up the class hierarchy at a later point in time.
> Add lambda input removal methods

- jlm/llvm/ir/operators/Phi.hpp
- jlm/llvm/opt/DeadNodeElimination.cpp
- tests/jlm/llvm/ir/operators/TestPhi.cpp
- tests/jlm/llvm/opt/TestDeadNodeElimination.cpp
This PR adds an API for phi input/output removal. It contains the following:
1. Add RemovePhiOutputsWhere and PrunePhiOutputs methods to phi node class
2. Add RemovePhiArgumentsWhere and PrunePhiArguments methods to phi node class
3. These implementations hide nasty implementation details, such as iteration order, from outside the class hierarchy
4. Removes the usage of RemoveInput, RemoveArgument, RemoveResult, and RemoveOutput from outside the structural node class hierarchy.
The implementations of RemovePhiOutputsWhere and RemovePhiArgumentsWhere will be simplified further down the road. The implementation details, such as iteration order, will be pushed further up the class hierarchy at a later point in time.
> Add phi input/output removal methods

- jlm/llvm/opt/DeadNodeElimination.cpp
- jlm/rvsdg/theta.hpp
- jlm/util/HashSet.hpp
- tests/jlm/rvsdg/test-theta.cpp
This PR adds an API for theta input/output removal. It contains the following:
1. Add RemoveThetaInputsWhere and PruneThetaInputs methods to the theta node class
2. Add RemoveThetaOutputsWhere and PruneThetaOutputs methods to the theta node class
3. These implementation hide nasty implementation details, such as iteration order, from outside the class hierarchy.
4. Removes the usage of RemoveInput, RemoveArgument, RemoveResult, and RemoveOutput from outside the structural node class hierarchy.
The implementation of RemoveThetaInputsWhere and RemoveThetaOutputsWhere will be simplified further down the road. The implementation details, such as iteration order, will be pushed further up the class hierarchy at a later point in time.
> Add theta input/output removal methods

- jlm/llvm/opt/reduction.cpp
This version should be possible to enable in the llvm-test-suite used by the CI.
> Disabled buggy optimizations in reduction (-Jred)

- jlm/llvm/ir/operators/call.hpp
- tests/jlm/llvm/ir/operators/TestCall.cpp
This PR closes #295. It makes the following changes:
1. Fixes a bug in the CallNode::Argument() method
2. Adds documentation to all call node accessors.
3. Adds a unit test for the accessors
> Improve call node accessors

- Makefile
- Makefile.sub
One target for applying clang formatting and one for dry run that only reports formatting errors.
> make: Added clang format targets

- jlm/llvm/opt/alias-analyses/PointsToGraph.cpp
- jlm/llvm/opt/alias-analyses/PointsToGraph.hpp
- jlm/rvsdg/view.cpp
- jlm/rvsdg/view.hpp
In practice this means the `PointsToGraph`'s dot output now adds an extra part to `RegisterNode`s, as seen here:
The names in parentheses correspond to the names given by rvsdg::view in the following output:
```
[]{
o0 := DELTA[MyList] 
[]{
o1 := ConstantPointerNull 
}[o1]
o2 := LAMBDA[next] o0 
[a3, a4, a5, a6 <= o0]{
o7 := BITS32(0) 
o8 := BITS32(4) 
o9 o10 := ALLOCA[ptr] o8 
o11 := MemStateMerge o10 a4 
o12 o13 := LOAD a6 o11 
o14 := STORE o9 o12 o13 
o15 o16 := LOAD o9 o14 
o17 := GetElementPtr o15 o7 o7 
o18 o19 := LOAD o17 o16 
o20 := STORE o9 o18 o19 
o21 o22 := LOAD o9 o20 
}[o21, a3, o22, a5]
}[o0, o2]
```
The example is generated by adding the following lines to the top of `TestAndersen.cpp`'s `TestLinkedList()`:
```cpp
std::unordered_map<const jlm::rvsdg::output*, std::string> …
```
> Add overloads for rvsdg::view and PointsToGraph::ToDot to allow giving the same unique names to outputs in both

- jlm/tooling/CommandGraphGenerator.cpp
- jlm/tooling/CommandGraphGenerator.hpp
We currently create intermediate files while compiling, but might run into problems when we compile in parallel as the intermediate file names are derived from the input file names. The intermediate file names were created by adding a suffix to the input file name. If we compile two input files with the same name in parallel, we create the same intermediate file names even though those two intermediate files originate from different input file names. This PR resolves this issue by adding some randomness into the intermediate file name. It solves this problems for the jlc and jhls command pipeline. Closes #312.
> Ensure creation of unique intermediate files throughout compilation

- jlm/tooling/CommandLine.cpp
- jlm/tooling/CommandLine.hpp
jlc and jlm-opt no longer support short hand optimization names such as red, cne, dne, etc.
> Remove deprecated command line options

- jlm/llvm/ir/operators/lambda.cpp
- tests/jlm/llvm/ir/operators/TestLambda.cpp
Add missing case of where a function is returned as a result of another function to the `ComputeCallSummary()` method. Closes #318.
> Add lambda result case to ComputeCallSummary() method

- jlm/llvm/ir/operators/operators.hpp
- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
- jlm/llvm/opt/alias-analyses/Steensgaard.hpp
- tests/TestRvsdgs.cpp
- tests/TestRvsdgs.hpp
- tests/jlm/llvm/opt/alias-analyses/TestSteensgaard.cpp
LLVM permits code where the number of call arguments mismatch with the number of lambda arguments, even though it is a direct call. A simple example would be:
```
unsigned int                                                                                           
foo ()                                                                                                 
{                                                                                                      
return 5;                                                                                            
}                                                                                                      
int                                                                                                    
main (void) …
```
> Handle mismatch of call/lambda arguments in Steensgaard

- jlm/tooling/CommandGraphGenerator.cpp
- jlm/util/Statistics.hpp
- jlm/util/file.hpp
- tests/jlm/util/Makefile.sub
- tests/jlm/util/TestFile.cpp
The CreateUniqueFile() method assumed so far that the directory provided needs to exist. This was a little bit too strict for some use cases. Simply drop this invariant. In addition, this PR also performs some minor clean ups. Closes #327.
> Drop JLM_ASSERT in CreateUniqueFile() method

- tools/jhls/jhls.cpp
- tools/jlm-hls/jlm-hls.cpp
Both tools now informs the user if they are used and jlm has not been compiled with the CRICT backend enabled. Closes #322.
> jhls and jlm-hls exits if CIRCT is not enabled

- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
1. Make MemoryLocation the base class of the ImportLocation class. This simplifies some code in the points-to graph construction pass.
2. Add documentation to the ImportLocation class.
3. Drop PointsToUnknown flag from imported memory locations. We know what they can point to, it is only to external memory and all memory locations that escaped from the module.
4. Move a FIXME that concerns the ImportLocation class also to the ImportLocation class
5. Add some documentation to the DummyLocation class
6. Clean up the AnalyzeImports method code a little bit.
This PR removes several FIXMEs from the code.
> Improve handling of imported entities in Steensgaard

- jlm/llvm/opt/alias-analyses/PointsToGraph.cpp
- jlm/llvm/opt/alias-analyses/PointsToGraph.hpp
- tests/jlm/llvm/opt/alias-analyses/Makefile.sub
- tests/jlm/llvm/opt/alias-analyses/TestPointsToGraph.cpp
This PR fixes four bugs introduced by this [PR](https://github.com/phate/jlm/pull/324):
1. It fixes the instantiation for the register-set node iterators. They were never instantiated and the code actually did not compile. A unit test was added that this cannot happen again.
2. The register-set nodes are now part of the DOT output. They were not printed before. :-/ This was only manually checked, and no unit test was added. We would need a graphviz data model to check this conveniently, i.e., without a string parsing mess.
3. It fixes the DebugString() method of the RegisterSetNode class. It segfaulted.
4. The iteration through the register set nodes of a points-to graph resulted in multiple visitations to the same register set nodes. The consequence was a messed up graphviz output. A …
> Fix several bugs in points-to graph

- jlm/llvm/ir/operators/load.cpp
- tests/jlm/llvm/opt/TestLoadMuxReduction.cpp
The load-mux reduction was unable to handle loads without state edges. This can happen when the compiler can statically determine that the address of the load is NULL. Even though this is an undefined program, the compiler should not panic and throw a hard error. This PR fixes the reduction and adds a unit test for this case.
Closes #331
Closes #323
> Fix load-mux reduction

- jlm/llvm/opt/alias-analyses/Andersen.cpp
- tests/jlm/llvm/opt/alias-analyses/TestAndersen.cpp
Instead of emitting one `PointsToGraph::RegisterNode` per `rvsdg::output*` represented in the PointsToGraph, it groups all `rvsdg::output*`s associated with the same `PointerObject`, and creates one `RegisterSetNode` for them. This should enable the future removal of `RegisterNode`s.
While translating the tests, I observed that the number of `RegisterSetNode`s was about 50-90% of the amount of `RegisterNode`s the test's PointsToGraph used to have, a nice improvement.
> Make Andersen emit PointsToGraphs with RegisterSetNodes

- jlm/llvm/opt/alias-analyses/AgnosticMemoryNodeProvider.cpp
- jlm/llvm/opt/alias-analyses/Andersen.cpp
- jlm/llvm/opt/alias-analyses/PointsToGraph.cpp
- jlm/llvm/opt/alias-analyses/PointsToGraph.hpp
- jlm/llvm/opt/alias-analyses/RegionAwareMemoryNodeProvider.cpp
- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
- tests/jlm/llvm/opt/alias-analyses/TestAndersen.cpp
- tests/jlm/llvm/opt/alias-analyses/TestPointsToGraph.cpp
- tests/jlm/llvm/opt/alias-analyses/TestSteensgaard.cpp
1. Removes the old PointsToGraph::RegisterNode class
2. Renames the PointsToGraph::RegisterSetNode class to PointsToGraph::RegisterNode
The graphviz output for the RegisterSetNodes was manually checked to contain the variable names of the debug output  and look "proper".
> Remove deprecated PointsToGraph::RegisterNode class

- .github/workflows/Doxygen.yml
- .github/workflows/tests.yml
- doxygen.conf
- jlm/llvm/frontend/InterProceduralGraphConversion.cpp
- jlm/llvm/ir/Annotation.cpp
- jlm/llvm/ir/aggregation.hpp
- jlm/llvm/ir/operators/Phi.hpp
- jlm/llvm/ir/operators/delta.hpp
- jlm/llvm/ir/operators/lambda.hpp
- jlm/llvm/opt/alias-analyses/AgnosticMemoryNodeProvider.hpp
- jlm/llvm/opt/alias-analyses/PointsToGraph.hpp
- jlm/llvm/opt/alias-analyses/Steensgaard.hpp
- jlm/rvsdg/node.hpp
- jlm/rvsdg/simple-node.hpp
1. Fixes all warnings and errors that doxygen produces when creating the documentation
2. Configures doxygen to fail when it encounters an error or warning
3. Moves documentation creation into its own workflow
> Add mandatory doxygen workflow

- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
- jlm/llvm/opt/alias-analyses/Steensgaard.hpp
- tests/TestRvsdgs.cpp
- tests/TestRvsdgs.hpp
- tests/jlm/llvm/opt/alias-analyses/TestSteensgaard.cpp
This PR introduces a points-to flag propagation pass in the Steensgaard alias analysis such that the points-to flags are properly propagated in the disjoint location set graph. So far, the points-to flags were only annotated for each disjoint location set, but were not propagated to the points-to set. However, all of the points-to flags are contagious, i.e., if a set is marked with a flag, then the points-to set must also be marked with it.
This should put the points-to flags on solid footing as:
1. The points-to flags are added for each location on creation time.
2. The flags are propagated to the root element of a set when a location is joined to a set.
3. The flags are propagated between sets with the just introduced propagation pass.
This PR introduces the third point from above. The …
> Propagate points-to flags between sets in Steensgaard

- jlm/llvm/opt/alias-analyses/Andersen.cpp
- jlm/llvm/opt/alias-analyses/Andersen.hpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.hpp
- jlm/tooling/CommandLine.cpp
- jlm/tooling/CommandLine.hpp
- jlm/util/Statistics.hpp
- tests/jlm/llvm/opt/alias-analyses/TestAndersen.cpp
Fixes #352
The tracked statistics have the same names as Steensgaard where applicable, but there are of course some differences.
`NumUnknownMemorySources_` became `NumExternalMemorySources_`, since Andersen only uses external.
Note that time spent connecting all PointingToExternal nodes to all Escaped nodes, is called `PointsToGraphConstructionExternalToEscapedTime[ns]`, since it is a subslice of  `PointsToGraphConstructionTime[ns]`.
The papers I've been reading about optimizing Andersen can have quite different internal representations for sets and set constraints, which means some of these statistics might change, but I will of course try to keep things stable when possible, to make comparisons possible.
> Add Statistics tracking to Andersen

- Makefile.macros
- tools/Makefile.sub
- tools/jhls/Makefile.sub
- tools/jlm-hls/Makefile.sub
1. Removes all extra CPPFLAGS from the executables in the project. These extra CPPFLAGS were never handled in the common_executable macro and are not necessary for a successful compilation.
2. Ensure consistent naming of EXTRA_LDFLAGS of the common_executable macro.
Closes #353
> Clean up common_executable build macro

- jlm/llvm/ir/RvsdgModule.hpp
- jlm/rvsdg/Makefile.sub
- jlm/rvsdg/RvsdgModule.hpp
1. Adds the RvsdgModule class. It should serve as top-level class for translation of modules in the future.
2. Utilize it as base class for the LLVM RVSDGModule class.
> Add Rvsdg module class

- jlm/hls/Makefile.sub
- jlm/hls/backend/rvsdg2rhls/DeadNodeElimination.cpp
- jlm/hls/backend/rvsdg2rhls/DeadNodeElimination.hpp
- jlm/hls/backend/rvsdg2rhls/rhls-dne.cpp
- jlm/hls/backend/rvsdg2rhls/rhls-dne.hpp
- jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.cpp
- tests/jlm/hls/backend/rvsdg2rhls/DeadNodeEliminationTests.cpp
This PR cleans up the HLS dead node elimination transformation. It does the following:
1. Introduces unit tests such that I am not completely blind while cleaning up.
2. Clean up the code such that I can easily refactor the RemoveInput, RemoveOutput, ... methods.
3. Document the shortcomings of the transformation in the unit tests.
Ultimately, this transformation should be incorporated into the DeadNodeElimination transformation.
> Clean up HLS dead node elimination transformation

- jlm/tooling/Command.hpp
- jlm/tooling/CommandGraphGenerator.cpp
- jlm/tooling/CommandLine.cpp
- jlm/tooling/CommandLine.hpp
- tools/jlm-hls/jlm-hls.cpp
This is the first step for eliminating the dependency on firtool and verilator by jhls.
To avoid this dependency the FIRRTL, harness, and remaning code is written to the specified output path.
> Moved output files from /tmp to output path

- .github/actions/BuildCirct/action.yml
- .github/workflows/hls.yml
- .github/workflows/tests.yml
Changed actions/checkout and actions/cache from v3 to v4, since v3 uses deprecated Node.js version.
> Changed CI actions to v4

- jlm/llvm/Makefile.sub
- jlm/llvm/ir/operators/load.cpp
- jlm/llvm/opt/reduction.cpp
- tests/jlm/llvm/opt/TestLoadStoreReduction.cpp
1. Fixes the load-store reduction. The problem was a missing check for the stored and loaded value type being the same. If they are not the same, then we might have to insert a truncation or conversion operation instead of just bypassing the load and store. I marked the place in the code with a FIXME such that we can improve upon it in the future.
2. Adds a unit test that exposes the problem.
Closes #302
> Enable load-store reduction again

- .github/workflows/tests.yml
By including `[Andersen]` in the PR title, an extra job is executed, running `make llvm-run-andersen` in the eval repo.
> [Andersen] Add conditional execution of llvm-run-andersen on PRs

- jlm/tooling/CommandLine.cpp
- jlm/tooling/CommandLine.hpp
We had a lot of unnecessary code for setting up the statistics command line options of jlm-opt and jlc. This PR simplifies it. It is part of #357.
> Simplify jlc and jlm-opt command line option setup

- jlm/llvm/backend/rvsdg2jlm/rvsdg2jlm.cpp
- jlm/llvm/frontend/InterProceduralGraphConversion.cpp
- jlm/llvm/opt/DeadNodeElimination.cpp
- jlm/llvm/opt/InvariantValueRedirection.cpp
- jlm/llvm/opt/OptimizationSequence.cpp
- jlm/llvm/opt/alias-analyses/AgnosticMemoryNodeProvider.hpp
- jlm/llvm/opt/alias-analyses/Andersen.cpp
- jlm/llvm/opt/alias-analyses/MemoryStateEncoder.cpp
- jlm/llvm/opt/alias-analyses/RegionAwareMemoryNodeProvider.hpp
- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
- jlm/llvm/opt/cne.cpp
- jlm/llvm/opt/inlining.cpp
- jlm/llvm/opt/inversion.cpp
- jlm/llvm/opt/pull.cpp
- jlm/llvm/opt/push.cpp
- jlm/llvm/opt/reduction.cpp
- jlm/llvm/opt/unroll.cpp
- jlm/util/Statistics.cpp
- jlm/util/Statistics.hpp
- tests/jlm/util/TestStatistics.cpp
The Statistics part of #382. Modifies all existing Statistics to provide the sourceFile path.
The mapping from id to name is now in `Statistics.cpp`, but many of the existing statistics used names that were different from the C++ enums, so I tried to make the classes keep their old names.
It might be better to have `GetName()` be an abstract method, and let subclasses provide names that way, instead of a single BijectiveMap. Let me know!
> Add measurement/timer system and sourceFile to Statistics base class

- Makefile.rules
- tests/Makefile.sub
With this change, a unit test failure is no longer "silent" but fails the entire build. It is user's choice if they want to abort on first failure (default invocation of make), or run all tests and have all failing ones reports (invoke as "make -k").
Closes #388
> Fail the build on unit test failure

- jlm/util/Makefile.sub
We forgot to add the libutil headers to the build system.
> Add missing libutil headers

- jlm/util/GraphWriter.cpp
- tests/jlm/util/TestGraphWriter.cpp
Apologies, but I realized I had mis-read the dot language spec. Unlike in HTML/XML, all attribute values must always be quoted. This PR fixes this. It is part of #308
> Fix non-quoted html attributes in dot output

- .github/actions/InstallPackages/action.yml
- .github/workflows/Doxygen.yml
- .github/workflows/hls.yml
1. Removes `sudo apt-get update`. It was unnecessary
2. Uses pip install lit instead of setup.py. Using setup.py is deprecated.
3. Only adds the llvm repository when it is not already present (multiple invocations of the script can lead to it)
4. Adds the possibility for installing doxygen and verilator to the script.
> Update InstallPackages composite action

- jlm/llvm/ir/operators/lambda.cpp
- jlm/llvm/ir/operators/lambda.hpp
- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
1. Introduces the IsExported() method to lambda nodes.
2. Utilizes this method in the Steensgaard analysis
3. Removes the old and incorrect is_exported() method.
The old method was not handling phi nodes correctly.
> Correctly detect exported lambda nodes in Steensgaard

- jlm/llvm/opt/alias-analyses/PointsToGraph.cpp
- jlm/llvm/opt/alias-analyses/PointsToGraph.hpp
- tests/jlm/llvm/opt/alias-analyses/TestPointsToGraph.cpp
This is used as part of double checking PointsToGraphs created by the naive constraint solver and more sophisticated solvers. If you think some of the lambdas should be available as separate public methods (or private methods) let me know.
> Add IsSupergraphOf to PointsToGraph

- .github/actions/BuildCirct/action.yml
- .github/actions/InstallPackages/action.yml
- scripts/build-circt.sh
1. Fixes the version of LLVM lit.
2. Fixes a bug in the provided paths to build-circt.sh.
3. Adds llvm-lit-path to build-circt.sh script.
Closes #423
> Fix build of CIRCT dependency in CI pipeline

- jlm/llvm/opt/alias-analyses/Andersen.cpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.hpp
- tests/jlm/llvm/opt/alias-analyses/TestPointerObjectSet.cpp
This is the first step in enabling both offline and online variable unification. You no longer have access to `PointerObeject`s directly, so all access goes through the set.
The global `constexpr bool ENABLE_UNIFICATION` allows quickly disabling unification logic, to check how much performance is lost due to extra lookups associated with the disjoint-set data structure, when unification isn't being used. I'm fairly confident that unification enables net performance gains. (Solvers that maintain their own unification invariants can get direct access to points-to sets to avoid the penalty, if it is too great).
Variables are not fully unified, they only start sharing points-to set. The old variables still exist, since other points-to sets may still contain only some of the variables in the …
> [Andersen] change the PointerObjectSet interface to enable unification

- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
- jlm/llvm/opt/alias-analyses/Steensgaard.hpp
- tests/TestRvsdgs.cpp
- tests/TestRvsdgs.hpp
- tests/jlm/llvm/opt/alias-analyses/TestAndersen.cpp
- tests/jlm/llvm/opt/alias-analyses/TestSteensgaard.cpp
The contents of registers that escape the module can point to external and all escaped memory, but they were not marked as points-to-external and points-to-escaped so far. This PR fixes this problem.
> Ensure correct flags for escaping registers in Steensgaard

- jlm/llvm/ir/operators/gamma.hpp
- jlm/llvm/opt/InvariantValueRedirection.cpp
- jlm/rvsdg/gamma.cpp
- jlm/rvsdg/gamma.hpp
- tests/jlm/rvsdg/test-gamma.cpp
1. Adds IsInvariant() method to gamma output class.
2. Replaces all usages of old is_invariant() function.
3. Removes is_invariant() function.
> Add IsInvariant() to gamma output class

- jlm/llvm/opt/alias-analyses/Andersen.cpp
- jlm/llvm/opt/alias-analyses/Andersen.hpp
- tests/jlm/llvm/opt/alias-analyses/TestAndersen.cpp
Since `RegisterNode`s support mapping multiple RVSDG outputs to a single `PointsToGraph` node, when they all share pointees, it makes sense to use this for unified `PointerObject`s of Register kind.
This PR also adds a test of `Andersen::ConstructPointsToGraphFromPointerObjectSet`, which was missing.
Just for fun, here is the PointsToGraph being built in the test:
> Make unified register PointerObjects share RegisterNode in the PointsToGraph

- jlm/llvm/Makefile.sub
- jlm/llvm/opt/alias-analyses/MemoryStateEncoder.cpp
- jlm/llvm/opt/alias-analyses/TopDownMemoryNodeEliminator.cpp
- jlm/llvm/opt/alias-analyses/TopDownMemoryNodeEliminator.hpp
- jlm/tooling/CommandLine.cpp
- jlm/util/Statistics.cpp
- jlm/util/Statistics.hpp
- tests/jlm/llvm/opt/alias-analyses/TestMemoryStateEncoder.cpp
- tests/jlm/llvm/opt/alias-analyses/TestTopDownMemoryNodeEliminator.cpp
This PR introduces the TopDownMemoryNodeEliminator. The TopDownMemoryNodeEliminator restricts the number of regions memory states need to be routed through by taking the lifetime of memory nodes into account. For example, the lifetime of a memory node originating from an `alloca` is at most the function the alloca is defined in.
The AgnosticMemoryNodeProvider and RegionAwareMemoryNodeProvider do not take such liftime information into account when producing a memory node provisioning. The idea of the TopDownMemoryNodeEliminator is to take the memory node provisioning produced by these memory node providers as seed provisioning and produce a new provisioning which takes the lifetime information into account. This simple example illustrates the idea:
```
static void
f(int x)
{
int* alloca; …
```
> Add TopDownMemoryNodeEliminator

- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
- tests/TestRvsdgs.cpp
- tests/TestRvsdgs.hpp
- tests/jlm/llvm/opt/alias-analyses/TestSteensgaard.cpp
The variadic arguments of external function calls were so far not handled and marked as escaped in Steensgaard. This PR fixes this.
> Mark variadic arguments of external calls as escaped in Steensgaard

- jlm/llvm/ir/operators/operators.hpp
- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
- jlm/llvm/opt/alias-analyses/Steensgaard.hpp
- jlm/rvsdg/control.hpp
- tests/TestRvsdgs.cpp
- tests/TestRvsdgs.hpp
- tests/jlm/llvm/opt/alias-analyses/TestSteensgaard.cpp
- tests/test-util.hpp
1. Fixes the handling of variadic arguments in Steensgaard for good.
2. Adds some RVSDG creators for different operations such that they are easier to create in the added unit test
3. Fixes the LLVM print function in test-util.hpp
4. Adds a variadic argument unit test.
> Fix handling of variadic arguments in Steensgaard

- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
- jlm/llvm/opt/alias-analyses/Steensgaard.hpp
The PR fixes the following issues:
1. Added handling of missing ptr2bits operation
2. Fix handling of ConstantArray and ConstantStruct. The insertion of the output location was performed in the loop for the nodes' inputs. This would lead to multiple creation attempts in case of multiple pointer inputs and therefore fail. Moreover, the handling of the nodes was changed by analyzing types instead of checking for previously created locations. This is more intuitive and in line with the handling of all other nodes.
3. Utilize GetOrInsertRegisterLocation() everywhere instead of InsertRegisterLocation(). The opposite was done in a recent PR, i.e., utilize InsertRegisterLocation() instead of the more general GetOrInsertRegisterLocation(), but this was simply incorrect and leads to bugs in case …
> Fix various issues in Steensgaard

- jlm/llvm/opt/alias-analyses/Andersen.cpp
- jlm/llvm/opt/alias-analyses/Andersen.hpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.hpp
- tests/jlm/llvm/opt/alias-analyses/TestPointerObjectSet.cpp
I had some issues where the order nodes were traversed seemed different in the "main" analysis and the "double check" analysis. To make debugging easier, the double check now makes use of a copy of the constraint set, instead of creating the constraint set again.
@phate I tried looking into the `rvsdg::topdown_traverser`, and realized I might have misunderstood it. I initially thought it traversed the region in a topological order (all predecessors of X are visited before X), but now I'm not quite sure, as it kind of looks like "at least one predecessor of X has been visited before X". My analysis has however assumed the order to be topological, without any issues. Do you know if that's just been luck, or if it is somehow guaranteed?
> Use clone of Andersen's variable and constraint set when double checking

- jlm/llvm/opt/alias-analyses/RegionAwareMemoryNodeProvider.cpp
- jlm/llvm/opt/alias-analyses/RegionAwareMemoryNodeProvider.hpp
1. Fixes an issue where memory nodes assigned to the region of a recursive call were not properly propagated upwards in the region tree. The issue arose as the method execution in the code was only executed conditionally even though it should have been unconditionally.
2. Splits up the single invariant check to two checks such that it is easier to deduce problems in the future.
3. Adds a debug method for printing annotated region trees.
Closes #281
Closes #201
> Ensure proper memory node propagation in RegionAwareMemoryNodeProvider

- jlm/llvm/opt/alias-analyses/Andersen.cpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.hpp
- tests/jlm/llvm/opt/alias-analyses/TestAndersen.cpp
- tests/jlm/llvm/opt/alias-analyses/TestPointerObjectSet.cpp
The flag `HasEscaped` is now reserved for memory objects only. It implies the `PointeesEscaping` flag. The latter flag can be applied to registers, and it is also shared between all PointerObjects in a unification.
This allows the worklist to properly handle unification.
> [Andersen] Split HasEscaped into two flags

- jlm/llvm/ir/operators/load.cpp
- jlm/llvm/ir/operators/load.hpp
- jlm/llvm/opt/reduction.cpp
- tests/jlm/llvm/ir/operators/TestLoad.cpp
This PR removes the load-store-alloca reduction.
The reduction was buggy (it failed when the stored and loaded value was of a different type) and it is also just a more specific version of the [load-store reduction](https://github.com/phate/jlm/blob/86d9af20fef46935ab31ae4fbcb840eed9f50180/jlm/llvm/ir/operators/load.cpp#L205C1-L213C25). Since the load-store reduction is more general, we can just remove this reduction instead of fixing it.
Closes #341
> Remove load-store-alloca reduction

- jlm/rvsdg/Makefile.sub
- jlm/tooling/Makefile.sub
We had test files missing in the Makefiles. I went through all the test listings in the Makefiles and compared to the files in the test folder to ensure that everything was added.
> Add missing tests to Makefiles

- .github/workflows/hls.yml
The HLS workflow performs a checkout of a specific jlm-eval-suite commit. This makes it possible to make updates to the jlm-eval-suite independently of jlm, and that later can be used by the jlm CI. This avoids breaking the CI until pull requests have been approved for both the jlm-eval-suite and jlm repositories.
> CI HLS workflow uses specific jlm-eval-suite commit

- jlm/llvm/opt/alias-analyses/Andersen.cpp
- jlm/llvm/opt/alias-analyses/Andersen.hpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.hpp
- jlm/util/GraphWriter.cpp
- jlm/util/GraphWriter.hpp
- tests/jlm/llvm/opt/alias-analyses/TestPointerObjectSet.cpp
- tests/jlm/util/TestGraphWriter.cpp
Also adds some utility functions to the GraphWriter classes, to make it nicer to use. At first I was surprised that `arrowtail` is completely ignored when edges have their default `dir=forward`, so it now selects a `dir` that makes manually specified arrow heads visible.
The subset graphs produced look like
Regular edges are superset constraints, dashed edges are complex constraints (dereference the side with the circle to convert it into a regular superset constraint edge).
The + means points to escaped, e means all the pointees in the set should escape. NOTRACK is for PointerObjects where the final PointsToGraph node doesn't get any pointees. Function call constraints don't use edges, so they are a bit harder to read.
For this PR, I have added another temporary environment variable …
> Add method for dumping the constraint set as a subset graph

- .github/actions/BuildJlm/action.yml
- .github/actions/InstallPackages/action.yml
- .github/workflows/tests.yml
The valgrind jobs are currently failing in several PRs as fetching the mirrors fails. This is due to a missing `apt-get update` before installing the package. This PR does the following:
1. Adds the valgrind installation to the InstallPackages composite action
2. Ensures that an `apt-get update` is performed before packages are installed
> Add valgrind to install packages composite action

- jlm/tooling/Command.cpp
- jlm/tooling/Command.hpp
- jlm/tooling/CommandLine.cpp
- jlm/tooling/CommandLine.hpp
- tests/jlm/tooling/TestJlmOptCommandLineParser.cpp
Adds an option to jlm-opt for printing an RVSDG in ASCII format.
> Add ascii output format option to jlm-opt

- jlm/util/HashSet.hpp
- tests/jlm/util/TestHashSet.cpp
@phate's comment about using `std::set` instead of `util::HashSet` made me remember why I picked `set` in the first place: `std::pair` doesn't have a specialization of `std::hash`. Since we have our own `HashSet` class that we like to use, I thought it would be fun to see what it would look like to add support for `std::pair`without requiring the user to specify a custom hash function for it.
I also added some constructors to be able to initialize the set with sets that do not have the same hash functor.
If we prefer to not go this route that is of course completely OK. I do enjoy being able to place `std::pair` in HashSets without any extra hassle, though.
> Add custom Hash functor for HashSet, with overload for std::pair

- jlm/llvm/Makefile.sub
- jlm/llvm/backend/jlm2llvm/instruction.cpp
- jlm/llvm/frontend/LlvmInstructionConversion.cpp
- jlm/llvm/ir/operators.hpp
- jlm/llvm/ir/operators/LoadVolatile.cpp
- jlm/llvm/ir/operators/LoadVolatile.hpp
- tests/jlm/llvm/backend/llvm/jlm-llvm/LoadTests.cpp
- tests/jlm/llvm/frontend/llvm/LoadTests.cpp
- tests/jlm/llvm/ir/operators/LoadVolatileTests.cpp
1. Add LoadOperation and LoadNode class for volatile load operations.
2. Adds conversion support for LLVM -> RVSDG
3. Adds conversion support for RVSDG -> LLVM
> Add support for volatile loads

- jlm/llvm/Makefile.sub
- jlm/llvm/backend/jlm2llvm/instruction.cpp
- jlm/llvm/frontend/LlvmInstructionConversion.cpp
- jlm/llvm/ir/operators.hpp
- jlm/llvm/ir/operators/LoadVolatile.hpp
- jlm/llvm/ir/operators/StoreVolatile.cpp
- jlm/llvm/ir/operators/StoreVolatile.hpp
- tests/jlm/llvm/backend/llvm/jlm-llvm/StoreTests.cpp
- tests/jlm/llvm/frontend/llvm/StoreTests.cpp
- tests/jlm/llvm/ir/operators/StoreVolatileTests.cpp
Add StoreOperation and StoreNode class for volatile load operations.
Adds conversion support for LLVM -> RVSDG
Adds conversion support for RVSDG -> LLVM
> Add support for volatile stores

- jlm/llvm/opt/reduction.cpp
I could not reproduce the problem from #307 any longer. Looking at the input program and the reported error, I suspect that this optimization was just the trigger, but not the actual cause. I believe that the cause was the missing loaded type in the equality operator of the LoadOperation. It was fixed in #456.
Closes #307
> Enable load-load-state reduction again

- jlm/llvm/backend/jlm2llvm/instruction.cpp
- jlm/llvm/frontend/LlvmInstructionConversion.cpp
- jlm/llvm/ir/operators/MemCpy.cpp
- jlm/llvm/ir/operators/MemCpy.hpp
- jlm/llvm/opt/alias-analyses/Andersen.cpp
- jlm/llvm/opt/alias-analyses/MemoryStateEncoder.cpp
- jlm/llvm/opt/alias-analyses/RegionAwareMemoryNodeProvider.cpp
- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
- tests/TestRvsdgs.cpp
- tests/jlm/llvm/backend/llvm/jlm-llvm/MemCpyTests.cpp
- tests/jlm/llvm/frontend/llvm/MemCpyTests.cpp
- tests/jlm/llvm/ir/operators/MemCpyTests.cpp
- tests/jlm/llvm/opt/alias-analyses/TestMemoryStateEncoder.cpp
The reason for this renaming is that a common operation will be introduced in order to:
1. Refactor out common properties between the volatile and non-volatile
operations/nodes.
2. Provide a common base class for passes, such as alias analysis, that
do not care about the volatile/non-volatile.
> Rename MemCpyOperation class to MemCpyNonVolatile

- jlm/llvm/Makefile.sub
- jlm/llvm/ir/operators/operators.cpp
- jlm/llvm/opt/alias-analyses/Operators.cpp
- jlm/llvm/opt/alias-analyses/Operators.hpp
- tests/jlm/llvm/ir/operators/MemoryStateOperationTests.cpp
- tests/jlm/llvm/opt/alias-analyses/MemoryStateOperationTests.cpp
The equality operator of all memory state operations was not taking the number of operands/results into account. This PR fixes this issue. An upcoming PR will move them in the same file and overhaul their implementation.
> Fix memory state operation equality

- jlm/llvm/Makefile.sub
- jlm/llvm/ir/types.hpp
- tests/jlm/llvm/ir/TestTypes.cpp
The diff should be self-explanatory :)
> Fix bug in isOrContains type helper function

- jlm/util/TarjanScc.hpp
- tests/jlm/util/TestTarjanScc.cpp
This does not affect correctness, but should boost performance by avoiding unnecessary visits of nodes that are already parts of finished SCCs.
When implementing DFS using a stack, I had forgotten that the same node can be added multiple times before it actually gets visited. In a graph like
```
A -------> B
\         ^
--> C --/
```
Visiting node A will push B and C. Since we then visit C first, it will also have to push B to process B before C can be popped. The edge `A->B` should then be ignored when popping B the second time.
> Perf: Avoid visiting nodes for a "second" time multiple times in TarjanSCC

- jlm/llvm/Makefile.sub
- jlm/llvm/frontend/InterProceduralGraphConversion.cpp
- jlm/llvm/ir/operators/Load.hpp
- jlm/llvm/ir/operators/Store.hpp
- tests/jlm/llvm/frontend/llvm/ThreeAddressCodeConversionTests.cpp
The three address code conversion for volatile loads and stores did not create the correct LoadVolatileNode and StoreVolatileNode classes, but simple_node classes.
1. Fix the three address code conversion for volatile loads
2. Fix the three address code conversion for volatile stores
3. Refactors the conversion to be better readable
4. Adds unit tests for the conversions
5. Adds support functions to easier test other conversions in the future
> Fix three address code conversion for volatile loads and stores

- jlm/llvm/ir/operators/Load.cpp
- jlm/llvm/ir/operators/Load.hpp
- jlm/llvm/ir/operators/Store.cpp
- jlm/llvm/ir/operators/Store.hpp
- jlm/llvm/opt/alias-analyses/Andersen.cpp
- jlm/llvm/opt/alias-analyses/Andersen.hpp
- jlm/llvm/opt/alias-analyses/MemoryStateEncoder.cpp
- jlm/llvm/opt/alias-analyses/MemoryStateEncoder.hpp
- jlm/llvm/opt/alias-analyses/RegionAwareMemoryNodeProvider.cpp
- jlm/llvm/opt/alias-analyses/RegionAwareMemoryNodeProvider.hpp
- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
- jlm/llvm/opt/alias-analyses/Steensgaard.hpp
1. Adds support for volatile load, store, and memcpy nodes to memory state encoder
2. Adds support for volatile load, store, and memcpy nodes to Steensgaard alias analysis
3. Adds support for volatile load, store, and memcpy nodes to Andersen alias analysis
4. Adds support for volatile load, store, and memcpy nodes to region-aware memory node provider
5. Tighten the handling of simple nodes in the memory state encoder
> Add support for volatile operations to alias analyses pipeline [Andersen] [SteensgaardAgnostic]

- jlm/llvm/opt/alias-analyses/Andersen.cpp
- jlm/llvm/opt/alias-analyses/Andersen.hpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.hpp
- jlm/rvsdg/graph.cpp
- tests/jlm/llvm/opt/alias-analyses/TestPointerObjectSet.cpp
This PR fixes a bug in the worklist solver where pointees could be added to `GetPointsToSet(node)`, while the points-to set was being iterated over.
Running the worklist is now divided into two functions, to convert runtime configuration into compile-time configuration through dispatching the corresponding templated version.
With this PR, the only configuration of the worklist solver is the worklist policy.
The default configuration checks an environment variable to be overridden. This is to make development easier, and not because I think environment variables are a good configuration interface :)
> [Andersen] Add queue for new edges to the worklist, and enable picking worklist policy

- jlm/rvsdg/Makefile.sub
- jlm/rvsdg/bitstring/arithmetic-impl.hpp
- jlm/rvsdg/bitstring/arithmetic.cpp
- jlm/rvsdg/bitstring/arithmetic.hpp
Remove all code generation macros for instantiating bitstring operation classes. Replace this with normal C++ template classes.
> Rework bitstring ops using templates instead of macros

- jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.cpp
- jlm/hls/backend/rvsdg2rhls/alloca-conv.cpp
- jlm/hls/backend/rvsdg2rhls/mem-queue.cpp
- jlm/hls/backend/rvsdg2rhls/mem-sep.cpp
- jlm/hls/backend/rvsdg2rhls/memstate-conv.cpp
- jlm/hls/backend/rvsdg2rhls/remove-unused-state.cpp
- jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.cpp
- jlm/llvm/backend/jlm2llvm/instruction.cpp
- jlm/llvm/frontend/LlvmInstructionConversion.cpp
- jlm/llvm/ir/operators/Load.cpp
- jlm/llvm/ir/operators/MemoryStateOperations.cpp
- jlm/llvm/ir/operators/MemoryStateOperations.hpp
- jlm/llvm/ir/operators/Store.cpp
- jlm/llvm/opt/alias-analyses/MemoryStateEncoder.cpp
- tests/TestRvsdgs.cpp
- tests/jlm/llvm/frontend/llvm/test-function-call.cpp
- tests/jlm/llvm/ir/operators/LoadTests.cpp
- tests/jlm/llvm/ir/operators/MemoryStateOperationTests.cpp
- tests/jlm/llvm/ir/operators/StoreTests.cpp
- tests/jlm/llvm/opt/TestLoadMuxReduction.cpp
- tests/jlm/llvm/opt/alias-analyses/TestMemoryStateEncoder.cpp
1. Rename the operations to consistent names
2. Adds some documentation
3. Cleans up some minor code smells
> Clean up memory state operations

- jlm/rvsdg/Makefile.sub
- jlm/rvsdg/bitstring/comparison-impl.hpp
- jlm/rvsdg/bitstring/comparison.cpp
- jlm/rvsdg/bitstring/comparison.hpp
Remove all code generation macros for instantiating bitstring comparison operation classes. Replace this with normal C++ template classes.
> Rework bitstring comparison ops using templates instead of macros

- jlm/llvm/backend/jlm2llvm/instruction.cpp
- jlm/llvm/frontend/LlvmInstructionConversion.cpp
- jlm/llvm/frontend/LlvmTypeConversion.cpp
- jlm/llvm/frontend/LlvmTypeConversion.hpp
- jlm/llvm/ir/attribute.cpp
- jlm/llvm/ir/attribute.hpp
- jlm/llvm/ir/operators/operators.hpp
- jlm/llvm/ir/operators/sext.hpp
- jlm/llvm/ir/types.cpp
- jlm/llvm/ir/types.hpp
- tests/TestRvsdgs.cpp
- tests/jlm/llvm/backend/llvm/jlm-llvm/test-type-conversion.cpp
- tests/jlm/llvm/ir/TestTypes.cpp
- tests/jlm/llvm/ir/operators/TestGetElementPtr.cpp
Convert llvm type attribute, base types as well as the type conversion routines to use shared_ptr<type>.
> Convert various llvm IR ops to shared_ptr of type

- jlm/hls/backend/rhls2firrtl/verilator-harness-hls.cpp
Instead of controlling which tracing format to be used at compile time of jlm it is now given as a -D flag when compiling the generated file with verilator.
> Configuration of tracing format moved to verilator command

- jlm/llvm/ir/RvsdgModule.hpp
- jlm/llvm/ir/cfg.hpp
- jlm/llvm/ir/ipgraph-module.hpp
- jlm/llvm/ir/operators/Load.hpp
- jlm/llvm/ir/operators/Store.hpp
- jlm/llvm/ir/operators/alloca.hpp
- jlm/llvm/ir/operators/operators.hpp
- jlm/llvm/ir/operators/sext.hpp
- jlm/llvm/ir/variable.hpp
- jlm/rvsdg/binary.hpp
- jlm/rvsdg/bitstring/arithmetic-impl.hpp
- jlm/rvsdg/bitstring/arithmetic.hpp
- jlm/rvsdg/bitstring/bitoperation-classes.hpp
- jlm/rvsdg/bitstring/comparison.hpp
- jlm/rvsdg/bitstring/concat.cpp
- jlm/rvsdg/bitstring/concat.hpp
- jlm/rvsdg/bitstring/slice.hpp
- jlm/rvsdg/control.cpp
- jlm/rvsdg/graph.hpp
- jlm/rvsdg/operation.hpp
- jlm/rvsdg/region.cpp
- jlm/rvsdg/region.hpp
- jlm/rvsdg/statemux.hpp
- jlm/rvsdg/structural-node.hpp
- jlm/rvsdg/unary.hpp
- tests/jlm/llvm/ir/TestAnnotation.cpp
- tests/jlm/llvm/opt/test-unroll.cpp
- tests/test-operation.hpp
- tests/test-types.cpp
- tests/test-types.hpp
Add overloaded constructors and/or creator functions that take "shared_ptr<const type>" instead of "const type &" arguments (and hence can take over reference from caller, instead of requiring a copy operation).
In some cases, the "type copy" methods can be removed as they have no callers anymore. For others, the superseded methods will be removed once all callers are converted.
This sets the groundwork for gradually converting all call sites to use shared type references.
> Add overloads to shared_ptr of type for various ops

- .github/workflows/tests.yml
We changed the make target for Andersen alias analysis with agnostic encoding in this [PR](https://github.com/phate/jlm-eval-suite/pull/31). Fix the CI to reflect this change.
> Fix make target for Andersen with agnostic encoding [AndersenAgnostic]

- jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.cpp
- jlm/hls/backend/rvsdg2rhls/alloca-conv.cpp
- jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.cpp
- jlm/llvm/backend/rvsdg2jlm/rvsdg2jlm.cpp
- jlm/llvm/ir/operators/operators.hpp
- jlm/llvm/opt/inversion.cpp
- jlm/llvm/opt/pull.cpp
- jlm/llvm/opt/push.cpp
- jlm/llvm/opt/unroll.cpp
- jlm/rvsdg/graph.cpp
- jlm/rvsdg/node.cpp
- jlm/rvsdg/node.hpp
- tests/jlm/llvm/opt/alias-analyses/TestMemoryStateEncoder.cpp
We had three incarnations of the same method for retrieving the node connected to an input. Remove two, keep one.
> Remove duplicate input_node() methods

- jlm/llvm/ir/operators/lambda.cpp
- jlm/llvm/ir/operators/lambda.hpp
- jlm/llvm/opt/alias-analyses/MemoryStateEncoder.cpp
- tests/TestRvsdgs.cpp
- tests/jlm/llvm/opt/alias-analyses/TestMemoryStateEncoder.cpp
1. Adds convenience methods to the lambda node for retrieving the memory state region argument or result.
2. Uses them to remove some FIXMEs in the memory state encoder.
3. Fixes an FreeNull RVSDG test where the memory state was not the last argument/result.
It is currently not enforced on lambda creation that the last argument/result of a lambda node needs to be a memory state. This is only enforced on the call nodes at the moment. The reason why we currently cannot enforce this is because the HLS dialect uses the same lambda, but without memory states. This tight coupling will hopefully be resolved in the near future and then we can start to enforce it on the lambda side as well.
> Add methods for retrieving memory states from lambda nodes [AndersenAgnostic][SteensgaardAgnostic]

- .gitignore
- Makefile
The user can write their own make targets in Makefile.custom, which is not tracked by git.
> Adds support for custom make targets

- jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.cpp
- jlm/hls/backend/rhls2firrtl/json-hls.cpp
- jlm/hls/backend/rvsdg2rhls/UnusedStateRemoval.cpp
- jlm/hls/backend/rvsdg2rhls/add-triggers.cpp
- jlm/hls/backend/rvsdg2rhls/alloca-conv.cpp
- jlm/hls/backend/rvsdg2rhls/dae-conv.cpp
- jlm/hls/backend/rvsdg2rhls/instrument-ref.cpp
- jlm/hls/backend/rvsdg2rhls/instrument-ref.hpp
- jlm/hls/backend/rvsdg2rhls/mem-conv.cpp
- jlm/hls/backend/rvsdg2rhls/mem-queue.cpp
- jlm/hls/backend/rvsdg2rhls/remove-unused-state.cpp
- jlm/hls/ir/hls.cpp
- jlm/hls/ir/hls.hpp
- jlm/llvm/backend/rvsdg2jlm/rvsdg2jlm.cpp
- jlm/llvm/frontend/ControlFlowRestructuring.cpp
- jlm/llvm/ir/types.cpp
- jlm/llvm/ir/types.hpp
- jlm/mlir/frontend/MlirToJlmConverter.cpp
- jlm/rvsdg/bitstring/slice.cpp
- jlm/rvsdg/bitstring/slice.hpp
- jlm/rvsdg/bitstring/type.cpp
- jlm/rvsdg/bitstring/type.hpp
- jlm/rvsdg/control.cpp
- jlm/rvsdg/control.hpp
- jlm/rvsdg/type.hpp
- tests/test-types.cpp
- tests/test-types.hpp
Remove type copying from all remaining places, convert HLS ops. Remove
the "copy" member function from all type classes. This concludes the transition
to use shared references for types, although some API cleanup is stilll desired.
> Finalize type shared_ptr support

- jlm/hls/backend/rvsdg2rhls/mem-queue.cpp
For the distributed memory disambiguation
> Make state gate independent of load user

- scripts/run-hls-test.sh
The test now runs in parallel by default.
Also bumps the hls-test-suite to the latest commit.
> Add parallel threads configuration to run-hls-test.sh

- scripts/build-circt.sh
- scripts/build-mlir.sh
Changed --get-commit-hash to use 'exit 0' and print to stdout instead of stderr.
> Build scripts fix for --get-commit-hash

- scripts/build-circt.sh
jlm relies on the FIRRTL to Verilog Dialects in CIRCT. So switched to a CIRCT version that compiles a reduced set of Dialects.
> Build reduced version of CIRCT

- .github/actions/BuildCirct/action.yml
- .github/actions/BuildMlirDialect/action.yml
Enables CIRCT and MLIR builds to always be saved if their build succeeds but the workflow they are part of fails. This eliminates the need to rebuild CIRCT and MLIR for CIs that fails.
> Always save CIRCT and MLIR builds

- configure.sh
- jlm/hls/Makefile.sub
- jlm/hls/backend/firrtl2verilog/FirrtlToVerilogConverter.cpp
- jlm/hls/backend/firrtl2verilog/FirrtlToVerilogConverter.hpp
- jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.hpp
- tools/jlm-hls/jlm-hls.cpp
Enables jlm-hls to directly generate Verilog as output.
> New firrtl2verilog HLS backend

- jlm/tooling/CommandGraphGenerator.cpp
This simplifies how HLS benchmarks are compiled and reduce their dependencies to only jlm binaries (jhls and jlm-hls) and Verilator.
> jhls links llvm-IR files and creates single object file

- .github/workflows/hls.yml
- scripts/run-hls-test.sh
With jlm-hls being able to generate Verilog there is no longer a need to use the firtool to convert FIRRTL to Verilog.
> Removes --firtool option from run-hls-test.sh

- .github/actions/InstallPackages/action.yml
This avoids having to change the version number in multiple places when updating LLVM version.
> Using llvm-version variable for CI InstallPackages

- jlm/tooling/Command.cpp
- jlm/tooling/Command.hpp
- jlm/tooling/CommandLine.cpp
- jlm/tooling/CommandLine.hpp
- tests/jlm/tooling/TestJlmOptCommand.cpp
- tests/jlm/tooling/TestJlmOptCommandLineParser.cpp
This PR adds the capability to print the region tree to `jlm-opt`. Here is an example output:
```
RootRegion
-DELTA[.str.3]
-DELTA[array2]
-DELTA[.str.2]
-DELTA[array]
-DELTA[__PRETTY_FUNCTION__.main]
-DELTA[.str.1]
-DELTA[.str]
-DELTA[points]
-LAMBDA[main]
--THETA
---GAMMA
----Region[0]
----Region[1]
--GAMMA
---Region[0]
---Region[1]
----GAMMA
-----Region[0]
-----Region[1]
------GAMMA
-------Region[0]
-------Region[1]
--------GAMMA
---------Region[0]
---------Region[1]
--------GAMMA
---------Region[0]
---------Region[1]
--GAMMA
---Region[0]
---Region[1]
```
> Add printing of rvsdg tree to jlm-opt

- jlm/llvm/ir/operators/call.cpp
- jlm/llvm/ir/operators/gamma.hpp
- jlm/llvm/opt/DeadNodeElimination.cpp
- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
- jlm/llvm/opt/cne.cpp
- jlm/rvsdg/gamma.cpp
- jlm/rvsdg/gamma.hpp
1. Introduces the GammaArgument class, which represents a region argument in a gamma subregion.
2. Removes the is_gamma_argument() function.
> Remove is_gamma_argument() function

- jlm/llvm/ir/operators/call.cpp
- jlm/llvm/ir/operators/theta.hpp
- jlm/llvm/opt/DeadNodeElimination.cpp
- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
- jlm/llvm/opt/cne.cpp
- jlm/rvsdg/theta.cpp
- jlm/rvsdg/theta.hpp
1. Introduces the ThetaArgument class, which represents a region argument in
a theta subregion.
2. Removes the is_gamma_argument() function.
> Remove is_theta_argument() function

- Makefile.rules
- jlm/hls/backend/rhls2firrtl/verilator-harness-hls.hpp
- jlm/tooling/Command.cpp
- jlm/tooling/CommandLine.cpp
It turns out `for` loops in `/bin/sh` will ignore the exit codes of all commands except the very last command they run. This allowed some formatting errors to sneak into `master`.
> Make the ClangFormat action fail on format errors

- jlm/rvsdg/region.cpp
- jlm/rvsdg/region.hpp
- jlm/util/AnnotationMap.hpp
- jlm/util/Makefile.sub
- tests/jlm/rvsdg/RegionTests.cpp
- tests/jlm/util/AnnotationMapTests.cpp
This PR adds support for annotations to region trees. Here is an example of how it will look like:
```
RootRegion
-STRUCTURAL_TEST_NODE
--Region[0]
--Region[1]
---STRUCTURAL_TEST_NODE
----Region[0]
----Region[1]
----Region[2] NumNodes:0 NumArguments:0
```
The plan is to use this for introducing a pass that enables the printing of RVSDG properties for debugging as well as metric gathering for pass evaluations.
> Add annotation support to region tree

- .gitignore
- configure.sh
- jlm/hls/backend/rvsdg2rhls/mem-sep.cpp
- jlm/hls/util/view.cpp
- jlm/mlir/Makefile.sub
- jlm/tooling/Makefile.sub
- scripts/build-circt.sh
- scripts/build-mlir.sh
- tests/jlm/rvsdg/RegionTests.cpp
- tools/Makefile.sub
- tools/jhls/Makefile.sub
- tools/jlm-hls/Makefile.sub
I was having an issue where tests of the command parser would fail due to some MLIR option, even when neither `--enable-mlir` nor `--enable-hls` are passed to `configure.sh`. That is a separate issue that should be fixed, but I thought it was about time I got MLIR and CIRCT running on my own machine anyway.
These changes should make the build scripts work no matter where LLVM is installed.
This is as a draft PR for now, to check that these changes do not break CI.
PS: Some `.cpp` files used symbols imported from the standard library indirectly, so I had to add some `#include <>` to make it work. I am on arch (btw), but I am guessing these changes will become necessary on Ubuntu eventually as well.
> Generalize CIRCT and MLIR jlm dialect build scripts

- jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.cpp
- jlm/hls/backend/rhls2firrtl/base-hls.cpp
- jlm/hls/backend/rhls2firrtl/base-hls.hpp
- jlm/hls/backend/rhls2firrtl/json-hls.cpp
Makes it possible to manually change the size of a pointer by changing GetPointerSizeInBits() in base-hls.cpp.
> HLS: Configurable pointer size

- jlm/rvsdg/region.cpp
- tests/jlm/rvsdg/ArgumentTests.cpp
The argument constructors did not check whether the type of the provided input is the same as the handed in type. In the future, these constructors should be refactored such that we either hand in an input or a simple type, but not both at the same time. This would avoid this check altogether.
Closes #555
> Add missing type check to argument constructors

- jlm/rvsdg/region.cpp
- tests/jlm/rvsdg/ResultTests.cpp
The result constructors did not check whether the type of the provided output is the same as the handed in type. In the future, these constructors should be refactored such that we either hand in an output or a simple type, but not both at the same time. This would avoid this check altogether.
Closes #556
> Add missing type check to result constructors

- jlm/hls/ir/hls.cpp
- jlm/hls/ir/hls.hpp
- jlm/llvm/ir/operators/Phi.cpp
- jlm/llvm/ir/operators/Phi.hpp
- jlm/llvm/ir/operators/delta.cpp
- jlm/llvm/ir/operators/delta.hpp
- jlm/llvm/ir/operators/lambda.cpp
- jlm/llvm/ir/operators/lambda.hpp
- jlm/rvsdg/gamma.cpp
- jlm/rvsdg/gamma.hpp
- jlm/rvsdg/region.cpp
- jlm/rvsdg/region.hpp
- jlm/rvsdg/theta.cpp
- jlm/rvsdg/theta.hpp
- tests/jlm/rvsdg/test-graph.cpp
- tests/test-operation.hpp
1. Introduces a Copy() method to the argument class.
2. The introduced method enables us to fix a bug in the copy() method of the region. Previously, arguments were not copied according to their argument subtypes, but simply a new instance of argument was created.
3. Add unit test.
This PR is a necessary step to get rid off ports.
> Add Copy() method to argument class

- jlm/hls/ir/hls.cpp
- jlm/hls/ir/hls.hpp
- jlm/llvm/ir/operators/Phi.cpp
- jlm/llvm/ir/operators/Phi.hpp
- jlm/llvm/ir/operators/delta.cpp
- jlm/llvm/ir/operators/delta.hpp
- jlm/llvm/ir/operators/lambda.cpp
- jlm/llvm/ir/operators/lambda.hpp
- jlm/rvsdg/gamma.cpp
- jlm/rvsdg/gamma.hpp
- jlm/rvsdg/region.cpp
- jlm/rvsdg/region.hpp
- jlm/rvsdg/theta.cpp
- jlm/rvsdg/theta.hpp
- tests/jlm/rvsdg/test-graph.cpp
- tests/test-operation.hpp
1. Introduces a Copy() method to the result class.
2. The introduced method enables us to fix a bug in the copy() method of
the region. Previously, results were not copied according to their
result subtypes, but simply a new instance of result was created.
3. Extend unit test.
This PR is a necessary step to get rid off ports.
> Add copy() method to result class

- jlm/llvm/Makefile.sub
- jlm/llvm/opt/alias-analyses/Andersen.cpp
- jlm/llvm/opt/alias-analyses/Andersen.hpp
- jlm/llvm/opt/alias-analyses/LazyCycleDetection.hpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.hpp
- tests/jlm/llvm/opt/alias-analyses/TestLazyCycleDetection.cpp
- tests/jlm/llvm/opt/alias-analyses/TestPointerObjectSet.cpp
When propagating along the edge a->b, it is because a has something new. If b already has everything a has, that might indicate that there is a path from b to a. Lazy cycle detection looks for such a path using a DFS from b, and unifies everything that is on such a path b->*->a. It tries at most once per edge.
> [AndersenAgnostic] Add lazy cycle detection as an optional technique for Andersen

- jlm/llvm/Makefile.sub
- jlm/llvm/opt/alias-analyses/Andersen.cpp
- jlm/llvm/opt/alias-analyses/Andersen.hpp
- jlm/llvm/opt/alias-analyses/DifferencePropagation.hpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.hpp
- tests/jlm/llvm/opt/alias-analyses/TestDifferencePropagation.cpp
- tests/jlm/llvm/opt/alias-analyses/TestPointerObjectSet.cpp
Adds difference propagation, which is one of the more "invasive" techniques, as it needs to intercept modifications to the points-to sets. When iterating over a points-to set, you sometimes only need the set of pointees that have been added since last visit, while you other times need all pointees.
For the flags, we get away with not intercepting the setting of them. Difference propagation can just remember if the flag was set the last time the work item was visited, which only takes up 2 bits per PointerObject.
> [AndersenAgnostic] Add difference propagation

- .github/actions/BuildJlm/action.yml
- .github/workflows/ClangFormat.yml
- README.md
- configure.sh
- jlm/hls/backend/rhls2firrtl/verilator-harness-hls.hpp
This PR started as a fix of formatting that changed with clang-format 18. I also noticed that the constructor had an unnecessary `const`, so I fixed that.
Looking into why this was not caught by the ClangFormat workflow, I saw that the `configure.sh` script's `--enable-mlir` "consumed" the `--enable-hls`, causing hls to not be enabled, which affects the set of files found by `make format-dry-run`.
In an attempt to make this not happen in the future, I made `configure.sh` complain and fail if the path you pass to `--enable-mlir` or `--enable-hls` is not a folder that exists. This forces the user to set up the folder first, but it should be helpful in preventing this type of mistake.
Formatting is a bit of a special case, as we want to "enable" hls and mlir without needing to install …
> make ClangFormat check HLS, and make it optional to specify CIRCT and MLIR install paths in configure.sh

- jlm/llvm/frontend/ControlFlowRestructuring.cpp
- jlm/llvm/opt/alias-analyses/Andersen.cpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.hpp
- jlm/util/Worklist.hpp
- tests/jlm/util/TestWorklist.cpp
Adds the dummy worklist, which only remembers if /anything/ has been pushed.
When given this "worklist", the solver instead performs topological sweeps across all work items.
> [AndersenAgnostic] Add the topological worklist solver to Andersen

- jlm/hls/backend/rvsdg2rhls/dae-conv.cpp
- jlm/hls/backend/rvsdg2rhls/mem-conv.cpp
- jlm/hls/ir/hls.cpp
- jlm/hls/ir/hls.hpp
This PR adds an argument subclass for the entry arguments of the HLS loop. This is necessary in order to make the `rvsdg::argument` class abstract.
> Add EntryArgument for HLS loop

- jlm/rvsdg/region.cpp
- jlm/rvsdg/region.hpp
- tests/jlm/rvsdg/ArgumentTests.cpp
- tests/jlm/rvsdg/RegionTests.cpp
- tests/jlm/rvsdg/ResultTests.cpp
- tests/jlm/rvsdg/test-graph.cpp
- tests/jlm/rvsdg/test-nodes.cpp
- tests/test-operation.hpp
1. Replaces all usages of `argument::create()` with `TestGraphArgument::Create()` in the unit tests.
2. Makes the argument class abstract
3. Minor clean ups in the argument class
4. Add documentation to argument class
> Make argument class abstract

- jlm/hls/backend/rvsdg2rhls/dae-conv.cpp
- jlm/hls/backend/rvsdg2rhls/mem-conv.cpp
- jlm/hls/ir/hls.cpp
- jlm/hls/ir/hls.hpp
1. Add the ExitResult class for representing result values before the HLS loop terminates
2. Replaces respective `result::create()` with `ExitResult::Create()` usages
> Add ExitResult for HLS loop

- jlm/hls/backend/rvsdg2rhls/UnusedStateRemoval.cpp
- jlm/hls/backend/rvsdg2rhls/add-triggers.cpp
- jlm/hls/backend/rvsdg2rhls/mem-conv.cpp
- jlm/hls/backend/rvsdg2rhls/remove-unused-state.cpp
- jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.cpp
- jlm/llvm/ir/operators/lambda.cpp
- jlm/llvm/ir/operators/lambda.hpp
- jlm/rvsdg/region.cpp
- jlm/rvsdg/region.hpp
- tests/jlm/rvsdg/RegionTests.cpp
- tests/jlm/rvsdg/ResultTests.cpp
- tests/jlm/rvsdg/test-graph.cpp
- tests/jlm/rvsdg/test-nodes.cpp
- tests/test-operation.hpp
1. Replaces all usages of `result::create()` in the unit tests with the appropriate subclasses.
2. Makes the result class abstract
3. Minor clean ups in the result class
4. Add documentation to result class
> Make result class abstract

- jlm/llvm/opt/RvsdgTreePrinter.cpp
- jlm/llvm/opt/RvsdgTreePrinter.hpp
- jlm/tooling/CommandGraphGenerator.cpp
- jlm/tooling/CommandLine.cpp
- tests/jlm/llvm/opt/RvsdgTreePrinterTests.cpp
- tests/jlm/tooling/TestJlmOptCommand.cpp
- tests/jlm/tooling/TestJlmOptCommandLineParser.cpp
1. Adds support for annotating the number of RVSDG nodes to the RVSDG tree in the RvsdgTreePrinter pass.
2. Adds support for controlling the annotations from jlm-opt
3. Adds a unit test for the printing of the introduced annotation
Usage: `jlm-opt --RvsdgTreePrinter -s /tmp --annotations=NumRvsdgNodes input.ll`
Example output:
```
RootRegion NumRvsdgNodes:2
-STRUCTURAL_TEST_NODE NumRvsdgNodes:2
--Region[0] NumRvsdgNodes:1
--Region[1] NumRvsdgNodes:1
```
> Add jlm-opt support for RVSDG tree annotations

- jlm/llvm/opt/OptimizationSequence.hpp
- jlm/tooling/Command.cpp
- jlm/tooling/Command.hpp
- jlm/tooling/CommandLine.cpp
- jlm/tooling/CommandLine.hpp
- tests/jlm/tooling/TestJlmOptCommand.cpp
- tests/jlm/tooling/TestJlmOptCommandLineParser.cpp
PR #593 made optimizations dynamically configurable, but also screwed up the invariant that an optimization was only created once. This PR restores this invariant and moves the optimization creation from the JlmOptCommandLineOptions class to JlmOptCommand class.
> Ensure jlm-opt creates only single instances of optimizations

- jlm/llvm/backend/jlm2llvm/jlm2llvm.cpp
1. Cleans up the basic block conversion in the LLVM backend
2. Assigns name "bb[0...]" to the basic block in the output
This PR is required for #586 in order to better follow the output. It is also part of the effort in #529.
Example output:
```
; Function Attrs: noinline nounwind optnone uwtable
define i64 @fac(i64 noundef %0) #0 {
bb0:
%1 = alloca i64, align 8
%2 = alloca i64, align 8
store i64 %0, ptr %2, align 8
store i64 1, ptr %1, align 8
br label %bb1
bb1:                                              ; preds = %bb4, %bb0
%3 = load i64, ptr %1, align 8
%4 = load i64, ptr %2, align 8
%5 = icmp ugt i64 %4, 1
br i1 %5, label %bb3, label %bb2
bb2:                                              ; preds = %bb1
br label %bb4
bb3:                                              ; preds = %bb1
%6 …
```
> Ensure deterministic basic block name in LLVM output

- Makefile.rules
- README.md
- jlm/hls/Makefile.sub
- jlm/llvm/Makefile.sub
- scripts/check_headers.sh
- tests/Makefile.sub
make target for header consistency checking
Provide a "check-headers" target that verifies whether all header files
are correctly correctly declared for the build system. This avoids cases
when a header is used, but not declared in any library build rule.
In principle, the build system should always be aware of every single file
used during build. Otherwise, this can cause problems, e.g. when a library
is built but the "install" rule misses headers that should go without,
hence publishing a broken package.
The present checking does not verify if the header is "assigned" to the library
that "uses" it (or some dependent library) -- that is difficult to express
in "make", but this check should be sufficient for the purposes of manually
rectifying any oversight.
Fix missing headers detected …
> Header consistency checking

- jlm/llvm/opt/RvsdgTreePrinter.cpp
- jlm/llvm/opt/RvsdgTreePrinter.hpp
- jlm/tooling/CommandLine.cpp
- tests/jlm/llvm/opt/RvsdgTreePrinterTests.cpp
- tests/test-operation.cpp
- tests/test-operation.hpp
1. Extends the structural test node with an interface for adding inputs/outputs/arguments/results
2. Add support for printing of memory state typed inputs/outputs to RvsdgTreePrinter class
3. Adds support for this annotation to jlm-opt
> Add NumMemoryStateInputsOutputs annotation to RvsdgTreePrinter

- jlm/llvm/Makefile.sub
- jlm/llvm/ir/cfg.cpp
- jlm/llvm/ir/cfg.hpp
- jlm/llvm/ir/print.cpp
- jlm/llvm/ir/print.hpp
- jlm/llvm/ir/tac.cpp
- jlm/llvm/ir/tac.hpp
- tests/jlm/llvm/backend/llvm/r2j/GammaTests.cpp
- tests/jlm/llvm/ir/ThreeAddressCodeTests.cpp
- tests/jlm/llvm/ir/test-cfg-node.cpp
- tests/jlm/llvm/ir/test-cfg-prune.cpp
- tests/jlm/llvm/ir/test-cfg-purge.cpp
- tests/jlm/llvm/ir/test-cfg-structure.cpp
- tests/jlm/llvm/ir/test-cfg-validity.cpp
- tests/jlm/llvm/ir/test-cfg.cpp
- tests/jlm/llvm/ir/test-ssa-destruction.cpp
The ascii output for the control flow graph is not easily readable. This is the first PR on improving it. It does the following:
1. Moves the functions for converting a CFG to ascii to the cfg class
2. Adds a unit test for the conversion of three address codes
In order to add a unit test for the CFG conversion, I first need to make the output more deterministic. This will happen in a follow up PR. This PR is part of issue #586
> Move CFG conversion to ascii to cfg class

- jlm/llvm/backend/dot/DotWriter.cpp
- jlm/util/GraphWriter.cpp
- scripts/build-circt.sh
- tests/jlm/llvm/backend/dot/DotWriterTests.cpp
- tests/jlm/util/TestGraphWriter.cpp
In order to make it easier to read the graphs, arguments and results only get their index. The number in parenthesis is the index of the corresponding input/output of the structural node if any.
Let me know if you prefer a different label.
Fixes #626
> rvsdg2dot use argument and result index as label

- jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.cpp
- jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.hpp
Provides support for memories with multiple read and/or write ports, e.g., BRAMs in AMD FPGAs.
> Generalize the memory response and request nodes to handle multiple memory ports

- jlm/llvm/backend/rvsdg2jlm/rvsdg2jlm.cpp
- jlm/llvm/ir/cfg.cpp
- jlm/llvm/ir/cfg.hpp
- jlm/llvm/ir/print.cpp
1. Ensure that CFG arguments are labeled after RVSDG to CFG conversion
2. Give readable labels to CFG nodes
3. Add missing newline after CFG printing
This PR is part of issue #586
> Improve output of Cfg::ToAscii() method

- jlm/llvm/opt/RvsdgTreePrinter.cpp
- jlm/llvm/opt/RvsdgTreePrinter.hpp
- jlm/util/iterator_range.hpp
Use `std::count_if()` instead of explicit iteration to compute relevant annotations in `RvsdgTreePrinter` class.
> Simplify annotation computations in RvsdgTreePrinter class

- jlm/llvm/opt/alias-analyses/Andersen.cpp
- jlm/llvm/opt/alias-analyses/Andersen.hpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.hpp
- jlm/llvm/opt/alias-analyses/PointsToGraph.cpp
- jlm/llvm/opt/alias-analyses/PointsToGraph.hpp
- jlm/util/Statistics.hpp
- jlm/util/Worklist.hpp
- tests/jlm/llvm/opt/alias-analyses/TestAndersen.cpp
- tests/jlm/llvm/opt/alias-analyses/TestDifferencePropagation.cpp
- tests/jlm/llvm/opt/alias-analyses/TestPointerObjectSet.cpp
- tests/jlm/util/TestWorklist.cpp
During work on the `andersen-no-flags` branch, some other changes were made as I discovered issues or wanted more statistics:
- There was a bug where Hybrid Cycle Detection could invalidate an iterator while using it.
- The topological Worklist algorithm has been made slightly less terrible by actually tracking work items now, and only visiting nodes that need to be visited during the sweep. The `ObserverWorklist` is now called the `WorkSet` instead, as that name describes its new job (an unordered worklist) better. This is likely closer to what has been done by Pearce07, but it still does not make it the best worklist iteration order.
- Make the `JLM_ANDERSEN_TEST_ALL_CONFIGS` environment variable take an integer controlling the amount of iterations each config should be used.
The bulk …
> [AndersenAgnostic] Backport fixes and expanded statistics for Andersen analysis

- jlm/rvsdg/node.cpp
- jlm/rvsdg/node.hpp
- jlm/rvsdg/region.cpp
- jlm/rvsdg/region.hpp
Introduce input::GetOwner and output::GetOwner as the canonical and type-generic way to determine what "kind" an output/input is (either output/input to a node or region argument/result).
Introduce TryGetOwnerNode and TryGetRegionParentNode as convenience API to easily match different node kinds.
> Introduce accessor and convenience API for node type matching

- jlm/rvsdg/region.cpp
- jlm/rvsdg/region.hpp
Make both RegionArgument and RegionResult non-abstract and provide "Create" functions. This allows slowly phasing out the derived argument and result classes, replacing them with just RegionArgument and RegionResult. This allows to remove a lot of boilerplate code as the number of classes to be implemented and matched shrinks noticably.
Later refactoring should rename the input/output classes and also allow to clean them up so they do not even need to be virtual anymore.
> Make RegionArgument and RegionResult instantiable

- .github/actions/BuildCirct/action.yml
The 'save-always: true' option is deprecated.
This version should have the advantage that even if the CI fails at a later step, the build should have already been saved and not require to be rebuilt when a fix is pushed.
> Updated caching for CI CIRCT build

- .github/workflows/CheckHeaders.yml
- .github/workflows/ClangFormat.yml
- .github/workflows/Doxygen.yml
- .github/workflows/hls.yml
- .github/workflows/tests.yml
Adds the `cancel-in-progress: true` option to our GitHub workflows, which triggers if another commit is made to the same PR. I my experience, we only care about the latest commit, which makes it wasteful to finish the old workflow when a new commit is added.
The exact code used in the PR is taken from [here](https://turso.tech/blog/simple-trick-to-save-environment-and-money-when-using-github-actions).
> Cancel GitHub workflow if another commit is made to the same PR

- jlm/llvm/opt/RvsdgTreePrinter.cpp
- jlm/llvm/opt/alias-analyses/Andersen.cpp
- jlm/llvm/opt/alias-analyses/Andersen.hpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.hpp
- tests/jlm/llvm/opt/alias-analyses/TestPointerObjectSet.cpp
Adds flags for soundly handling any potential pointer smuggling through loading or storing pointers as scalars
Also includes some small changes:
- Add counts of the different types of PointerObject to the statistics
- Add `#include <algorithm>` to a file because I needed that to compile it.
- Fix bug where OnlineCD would never be combined with DP or PIP.
- Add environment variable option for using a specific config.
> [AndersenAgnostic] add flags for soundly handling pointer smuggling through loads and stores of scalar values

- jlm/llvm/ir/operators/Load.cpp
- tests/jlm/llvm/ir/operators/LoadTests.cpp
1. Splits up all load tests into their own unit tests
2. Fixes the duplicate state normalization for load nodes
> Fix duplicate state normalization for load nodes

- .github/actions/BuildCirct/action.yml
- .github/actions/InstallPackages/action.yml
- README.md
- scripts/build-circt.sh
- scripts/build-mlir.sh
- scripts/run-hls-test.sh
- scripts/run-llvm-test-suite.sh
- scripts/run-polybench.sh
The updated hashes give us a smaller CIRCT build, and cleaner output from the hls-test-suite, plus disables the problem test `test_memory_5`.
The other fixes include:
- avoid crashing if `lit` is not found immediately (it can be supplied using the option instead)
- avoid looping indefinitely when seeing unknown options
- make the scripts a little more consistent
> Make small fixes to scripts + update commit hashes of CIRCT and hls-test-suite

- scripts/run-hls-test.sh
If the git repository already existed, then updates of the run-hls-test.sh script could cause the git hash to not exist as the repo never got updated.
> Fetch hls-test repo if already cloned

- jlm/llvm/ir/operators/Load.cpp
- jlm/llvm/ir/operators/Load.hpp
- jlm/rvsdg/Makefile.sub
- jlm/rvsdg/NodeNormalization.hpp
- tests/jlm/llvm/ir/operators/LoadTests.cpp
This PR is the first in a series of PRs to remove the old node normalization interface that is intertwined in the RVSDG library. This PR does the following:
1. Adds a new and simple node normalization interface for optimizing the operands of a node. This enables to create individual instances of normalizations and therefore pass them around, and/or configure optimization by simply providing these instances instead of utilizing the flags of the old interface.
2. Converts the load reductions to this new interface
3. Utilizes these new reductions in load tests
> Add new normalization interface and convert load reductions to it

- .clang-tidy
- .github/actions/InstallPackages/action.yml
- .github/workflows/ClangTidy.yml
- Makefile.rules
- jlm/llvm/backend/jlm2llvm/instruction.hpp
- jlm/llvm/frontend/LlvmInstructionConversion.hpp
- jlm/llvm/opt/InvariantValueRedirection.hpp
- jlm/llvm/opt/alias-analyses/MemoryStateEncoder.hpp
- jlm/llvm/opt/alias-analyses/Steensgaard.hpp
- jlm/llvm/opt/unroll.hpp
- jlm/util/AnnotationMap.hpp
- jlm/util/intrusive-hash.hpp
This PR adds support for clang-tidy to the CI. It does not enforce any checks yet, but only adds the necessary infrastructure and fixes the problems in the code such that clang-tidy finishes without errors. Relevant checks will be added in future PRs.
Close #313
> Add clang-tidy support to CI

- jlm/llvm/ir/operators/Store.cpp
- tests/jlm/llvm/ir/operators/StoreTests.cpp
1. Splits up all store tests into their own unit tests
2. Fixes the duplicate state normalization for store nodes
> Fix duplicate state normalization for store nodes

- jlm/llvm/opt/alias-analyses/EliminatedMemoryNodeProvider.hpp
- jlm/llvm/opt/alias-analyses/Optimization.cpp
- jlm/tooling/Command.cpp
- jlm/tooling/CommandLine.cpp
- jlm/tooling/CommandLine.hpp
This PR adds the `AAAndersenTopDownLifetimeAware` optimization. It builds on the existing `Andersen` alias analysis in combination with the `TopDownMemoryNodeEliminator`.
> Add andersen top down lifetime aware optimization to jlm-opt

- jlm/rvsdg/simple-node.cpp
- jlm/rvsdg/simple-node.hpp
Add constructor as well as helper function to create simple and its operator in a single call. Allow to move the created operator in (instead of copying it).
> SimpleNode: convenience builder functions

- jlm/llvm/Makefile.sub
- jlm/llvm/backend/jlm2llvm/instruction.cpp
- jlm/llvm/ir/operators/FunctionPointer.cpp
- jlm/llvm/ir/operators/FunctionPointer.hpp
- jlm/llvm/opt/InvariantValueRedirection.cpp
- jlm/llvm/opt/alias-analyses/RegionAwareMemoryNodeProvider.cpp
- jlm/llvm/opt/alias-analyses/TopDownMemoryNodeEliminator.cpp
Add function / pointer conversion llvm operators. Accept these operators as top-level nodes in the various transformation passes, and handle them in instruction conversion.
There are presently no "users" of these operators or anything that puts them into the graph -- so this is preparatory for making function and pointer distinction in a later commit.
> Function pointer conversion

- .github/workflows/hls.yml
- scripts/run-hls-test.sh
If the cycle count for one or more of the hls test suite benchmarks results in a different cycle count than expected, then a comment is generated that appears in the PR.
> Generate comment in PR from CI if cycles differ

- jlm/llvm/opt/DeadNodeElimination.cpp
- jlm/rvsdg/theta.cpp
- jlm/rvsdg/theta.hpp
- tests/jlm/rvsdg/test-theta.cpp
Restructure dead node elimination such that it never requires "unbalanced" theta inputs / outputs -- interleave cleaning up the subregion instead.
Remove the support from theta node to deal with temporary invariant violation by inbalanced input / output. Introduce a method instead that can remove loop-invariant dead variables. It turns out that this is all that dead node elimination needs in practice.
> Clean up theta dead node elimination

- jlm/rvsdg/binary.cpp
- jlm/rvsdg/bitstring/concat.cpp
- jlm/rvsdg/bitstring/value-representation.hpp
- tests/jlm/rvsdg/bitstring/bitstring.cpp
Converts more tests to the new reduction interface and fixes 1 bug that occurred while doing so.
> Convert more tests to the new reduction interface

- jlm/hls/backend/rvsdg2rhls/add-prints.cpp
- jlm/hls/backend/rvsdg2rhls/instrument-ref.cpp
- jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.cpp
- jlm/llvm/frontend/InterProceduralGraphConversion.cpp
- jlm/llvm/frontend/LlvmInstructionConversion.cpp
- jlm/llvm/ir/RvsdgModule.cpp
- jlm/llvm/ir/RvsdgModule.hpp
- jlm/llvm/ir/ipgraph.cpp
- jlm/llvm/ir/operators.hpp
- jlm/llvm/ir/operators/call.hpp
- jlm/llvm/ir/operators/lambda.cpp
- jlm/llvm/opt/alias-analyses/Andersen.cpp
- jlm/llvm/opt/alias-analyses/Andersen.hpp
- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
- jlm/llvm/opt/alias-analyses/Steensgaard.hpp
- tests/TestRvsdgs.cpp
- tests/jlm/llvm/backend/llvm/r2j/test-recursive-data.cpp
- tests/jlm/llvm/ir/operators/TestCall.cpp
- tests/jlm/llvm/ir/operators/TestLambda.cpp
- tests/jlm/llvm/ir/operators/TestPhi.cpp
- tests/jlm/llvm/opt/TestDeadNodeElimination.cpp
- tests/jlm/llvm/opt/alias-analyses/TestAndersen.cpp
- tests/jlm/llvm/opt/alias-analyses/TestMemoryStateEncoder.cpp
- tests/jlm/llvm/opt/test-cne.cpp
- tests/jlm/llvm/opt/test-inlining.cpp
Make the lambda operator return a "function" object (instead of pointer) and make the call operator require a "function" object (instead of a pointer). Introduce pointer-to-function and function-to-pointer conversions in places where references to functions are stored in machine data structures or passed as machine-representable values across functions.
In pointer analysis, unify functions and pointers to functions as the same objects. Possibly function objects should be represented as "pointees" instead, but for now simply blurring the distinction between the two delivers the desired results.
> Distinguish between "function" and "pointer" types

- jlm/hls/ir/hls.cpp
- jlm/hls/ir/hls.hpp
- jlm/llvm/frontend/InterProceduralGraphConversion.cpp
- jlm/llvm/ir/operators/Load.cpp
- jlm/llvm/ir/operators/Load.hpp
- jlm/llvm/ir/operators/Phi.cpp
- jlm/llvm/ir/operators/Phi.hpp
- jlm/llvm/ir/operators/Store.cpp
- jlm/llvm/ir/operators/Store.hpp
- jlm/llvm/ir/operators/call.cpp
- jlm/llvm/ir/operators/call.hpp
- jlm/llvm/ir/operators/delta.cpp
- jlm/llvm/ir/operators/delta.hpp
- jlm/llvm/ir/operators/lambda.cpp
- jlm/llvm/ir/operators/lambda.hpp
- jlm/rvsdg/gamma.cpp
- jlm/rvsdg/gamma.hpp
- jlm/rvsdg/node.cpp
- jlm/rvsdg/node.hpp
- jlm/rvsdg/simple-node.cpp
- jlm/rvsdg/simple-node.hpp
- jlm/rvsdg/structural-node.cpp
- jlm/rvsdg/structural-node.hpp
- jlm/rvsdg/theta.cpp
- jlm/rvsdg/theta.hpp
- tests/test-operation.cpp
- tests/test-operation.hpp
Merge two commits:
1.  Make node operations type-safe
Only override Node::GetOperation in the most derived subclasses, and
let them store properly typed operation classes (instead of downcasting
them on each access).
This later also allows to more flexibly handle contents of operations in
a node-specific fashions.
2.  Avoid operator copy on construction of SimpleNode
Remove remaining constructor of SimpleNode that makes a copy of the given
operator. Leave only the one that allows moving an operator in.
This moves the architecture further towards making the nodes mostly "shells"
that contain graph-connectivity information, while the business logic is associated
with the operators.
> Node operator type safety

- jlm/llvm/Makefile.sub
- jlm/llvm/backend/jlm2llvm/instruction.cpp
- tests/jlm/llvm/backend/llvm/jlm-llvm/test-ignore-memory-state.cpp
This PR fixes the compiler crash mentioned in #703 by skipping over `UndefValueOperation`s with a return type of `MemoryStateType` in the `jlm2llvm` backend. These operations are generated during `MemoryStateEncoder::EncodeCallEntry` after using the lifetime aware optimization added in #703.
> Ignore UndefValueOperation returning MemoryStateType in llvm backend.

- jlm/rvsdg/theta.cpp
This PR adds a missing include which is needed for the `std::sort` in `jlm/rvsdg/theta.cpp` introduced in #720. The include seems not to be needed in the CI build but is necessary on Fedora 41 with LLVM compiled from source.
> Add missing #include <algorithm>.

- jlm/llvm/backend/dot/DotWriter.cpp
- jlm/rvsdg/graph.cpp
- jlm/rvsdg/graph.hpp
- jlm/rvsdg/node.cpp
- jlm/rvsdg/region.cpp
- jlm/rvsdg/region.hpp
- jlm/util/GraphWriter.cpp
- tests/jlm/llvm/backend/dot/DotWriterTests.cpp
It was a bit annoying to only see "a1", "r5" in the root RVSDG region, so this change makes use of "debug_string()" on inputs, outputs, results and arguments.
The `debug_string()` method was not overridden by the subclasses, so I added that. In general they were not really used anywhere, so adding the extra info did not break anything existing.
Finally, since I was touching the graph output, I decided to reduce the margins on argument and result nodes, which were previously very big.
> Make use of debug_string() for arguments and results in dot output

- jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.cpp
- jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.hpp
- jlm/tooling/Command.cpp
- jlm/tooling/Command.hpp
- jlm/tooling/CommandGraphGenerator.cpp
- jlm/tooling/CommandLine.cpp
- jlm/tooling/CommandLine.hpp
- jlm/util/Statistics.cpp
- jlm/util/file.hpp
- tests/jlm/llvm/opt/RvsdgTreePrinterTests.cpp
- tests/jlm/tooling/TestJlcCommandGraphGenerator.cpp
- tests/jlm/tooling/TestJlmOptCommand.cpp
- tests/jlm/util/TestFile.cpp
- tests/jlm/util/TestStatistics.cpp
- tools/jlm-hls/jlm-hls.cpp
In a couple of places `std::string` was used for file paths, which I changed.
Makes the constructor of `jlm::util::filepath` explicit, which exposed a few places where implicit conversions were used.
In order to make it more ergonomic to use `filepath`, an overload for `Join` taking a string was added, and `WithSuffix` was added.
`filepath` also got a helper for getting the path to the temp directory.
> Make use of jlm::util::filepath where applicable

- jlm/tooling/Command.cpp
- jlm/tooling/Command.hpp
This PR gives the `Command` class a default implementation of `Run()`, which does what most subclasses did already, but prints the command when the command fails.
> Print the failing command when subprocesses fail

- jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.cpp
- jlm/hls/backend/rhls2firrtl/json-hls.cpp
- jlm/hls/backend/rhls2firrtl/verilator-harness-hls.cpp
- jlm/hls/backend/rvsdg2rhls/UnusedStateRemoval.cpp
- jlm/hls/backend/rvsdg2rhls/add-triggers.cpp
- jlm/hls/backend/rvsdg2rhls/instrument-ref.cpp
- jlm/hls/backend/rvsdg2rhls/mem-conv.cpp
- jlm/hls/backend/rvsdg2rhls/remove-unused-state.cpp
- jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.cpp
- jlm/llvm/Makefile.sub
- jlm/llvm/backend/rvsdg2jlm/rvsdg2jlm.cpp
- jlm/llvm/frontend/InterProceduralGraphConversion.cpp
- jlm/llvm/ir/LambdaMemoryState.cpp
- jlm/llvm/ir/LambdaMemoryState.hpp
- jlm/llvm/ir/operators/lambda.cpp
- jlm/llvm/ir/operators/lambda.hpp
- jlm/llvm/opt/InvariantValueRedirection.cpp
- jlm/llvm/opt/alias-analyses/MemoryStateEncoder.cpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.cpp
- jlm/llvm/opt/alias-analyses/PointerObjectSet.hpp
- jlm/mlir/backend/JlmToMlirConverter.cpp
- tests/TestRvsdgs.cpp
- tests/jlm/llvm/opt/InvariantValueRedirectionTests.cpp
- tests/jlm/llvm/opt/alias-analyses/TestMemoryStateEncoder.cpp
- tests/jlm/llvm/opt/test-inlining.cpp
Remove all non-orthogonal convenience member functions (i.e.
functions reaching from lambda::node into lambda::operation).
Redudant helpers may save typing, but generally cause churn
during decoupling.
Extract memory state modelling from lambda node: The modelling
is quite specific to how llvm-level transformations represent functions
etc. Everything related to that modelling should probably be
consolidated into a location (i.e. the "memory encoding bits")
rather than being spread out to the pieces they apply to.
Move argument attributes to lambda operation: This removes the last
bit of state from the lambda node which now really only contains graph
structural information.
Moving the attributes also has the effect of subjecting them to implicit
copy, removing the need to manually copy …
> Clean up API of lambda node before RVSDG move

- jlm/util/BijectiveMap.hpp
When I originally wrote `BijectiveMap`, I wrote the iterator interface as a thin wrapper around the forward mapping's `cbegin()` and `cend()`.
The iterator you get from `cbegin()` has the reference type `const std::pair<const Key, Value> &`.
To achieve some symmetry, I added an additional `const` to get `const std::pair<const K, const V> &`.
Later it turned out that a `std::pair` or `std::unordered_map` with added `const` behaves very unergonomically. When the STL gives a `std::pair<const Key, Value>` it almost feels like an ugly hack to make only the `first` immutable. Trying to add additional `const` for symmetry only makes the assignment operator break in weird ways, and only on some systems.
In practice all I want is for the iterator to return `const std::pair<Key, Value> &`, but …
> Make BijectiveMap compile on more machines by avoiding const

- jlm/util/HashSet.hpp
- tests/jlm/util/TestHashSet.cpp
I had a use for this method in the Andersen-work, and thought I would backport it as I am likely to want to use it again.
With this operation, there are two possible implementations. I try to pick the one that should be the fastest, but I have not done benchmarking to figure out exactly where one implementation becomes faster than the other.
> add HashSet::DifferenceWith method

- .github/actions/BuildJlm/action.yml
- .github/actions/BuildMlirDialect/action.yml
- .github/workflows/ClangTidy.yml
- scripts/build-mlir.sh
Takes a lot of inspiration from the existing action `BuildCirct/action.yml`
Also changes the installation directory from `JLM_ROOT/lib/mlir-rvsdg` into `JLM_ROOT/build-mlir/usr`, which is closer to what CIRCT uses (`JLM_ROOT/build-circt/circt`).
> Fix incorrect cache key of MLIR Dialect built in CI

- jlm/mlir/backend/JlmToMlirConverter.cpp
- jlm/mlir/frontend/MlirToJlmConverter.cpp
- scripts/build-mlir.sh
- tests/jlm/mlir/TestJlmToMlirToJlm.cpp
This PR adds roundtripping of the mentioned nodes together with tests for this functionality. 
Depends changes to the [dialect](https://github.com/EECS-NTNU/mlir_rvsdg/pull/4/commits/51889684abf9f64dac8d051ee6a71a0a78827860).
> MLIR roundtrip of Alloca, Load and Store operations (Non-volatile)

- jlm/hls/Makefile.sub
- jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.cpp
- jlm/hls/opt/IOBarrierRemoval.cpp
- jlm/hls/opt/IOBarrierRemoval.hpp
- jlm/llvm/Makefile.sub
- jlm/llvm/backend/jlm2llvm/instruction.cpp
- jlm/llvm/frontend/LlvmInstructionConversion.cpp
- jlm/llvm/ir/operators/IOBarrier.cpp
- jlm/llvm/ir/operators/IOBarrier.hpp
- jlm/llvm/opt/alias-analyses/Andersen.cpp
- jlm/llvm/opt/alias-analyses/Andersen.hpp
- jlm/llvm/opt/alias-analyses/Steensgaard.cpp
- jlm/llvm/opt/alias-analyses/Steensgaard.hpp
- tests/jlm/hls/opt/IOBarrierRemovalTests.cpp
This PR introduces the IOBarrier operation and adds support for it to the LLVM and HLS dialect. The IOBarrier operation is necessary to sequentialize operations with potentially undefined behavior, such as division and modulo by zero as well as load and store operations from null pointers, to ensure correct program semantics. For example, the following code requires a IOBarrier to avoid unwanted undefined behavior:
```
int f(int x, int y)
{
opaque(); // calls internally exit(0)
return x / y;
}
```
The program is a valid C program under all circumstances, even if y equals zero. In order to capture this semantic, it is necessary to sequentialize the division operation below the call to opaque in the RVSDG. This is accomplished using the IOBarrier operation. If it can be proven that an …
> Add support for IOBarrier [AndersenAgnostic][SteensgaardAgnostic]

- jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.cpp
- jlm/llvm/backend/jlm2llvm/instruction.cpp
- jlm/llvm/frontend/LlvmInstructionConversion.cpp
- jlm/llvm/ir/operators/IntegerOperations.cpp
- jlm/llvm/ir/operators/IntegerOperations.hpp
This PR replaces the old bitstring comparison operations with new LLVM specific
integer comparison operations. The implementations have currently still
the following limitations:
1. The operations still use the bistring type. The type will potentially be
later replaced by an LLVM specific type.
2. No operation specific reductions have been implemented yet. This will
also happen in a follow-up PR.
At this point, the implementation only tries to get on par with the
respective bitstring operations (minus the reductions). More LLVM
specific semantics are going to be introduced in a future PR.
> Add LLVM-specific integer comparison operations

- jlm/llvm/backend/jlm2llvm/jlm2llvm.cpp
- jlm/llvm/frontend/ControlFlowRestructuring.cpp
- jlm/llvm/frontend/LlvmModuleConversion.cpp
- jlm/llvm/ir/aggregation.cpp
- jlm/llvm/ir/cfg-node.cpp
- jlm/llvm/ir/cfg-node.hpp
- jlm/llvm/ir/cfg-structure.cpp
- jlm/llvm/ir/cfg.cpp
- jlm/llvm/ir/domtree.cpp
- jlm/llvm/ir/print.cpp
- jlm/llvm/ir/ssa.cpp
- jlm/util/Makefile.sub
- jlm/util/PtrIterator.hpp
- tests/jlm/llvm/backend/llvm/r2j/GammaTests.cpp
- tests/jlm/llvm/frontend/llvm/LlvmPhiConversionTests.cpp
- tests/jlm/llvm/frontend/llvm/LoadTests.cpp
- tests/jlm/llvm/frontend/llvm/MemCpyTests.cpp
- tests/jlm/llvm/frontend/llvm/StoreTests.cpp
- tests/jlm/llvm/frontend/llvm/TestFNeg.cpp
- tests/jlm/llvm/frontend/llvm/test-function-call.cpp
- tests/jlm/llvm/frontend/llvm/test-restructuring.cpp
- tests/jlm/llvm/frontend/llvm/test-select.cpp
- tests/jlm/llvm/ir/test-cfg-structure.cpp
- tests/jlm/util/TestPtrIterator.cpp
While doing other things, I was annoyed with the iterator interfaces for accessing in-edges and out-edges on cfg nodes not implementing everything needed to be regarded as real iterators.
I added a helper class for wrapping iterators to pointers, to become an iterator to the pointees instead. It works for both raw pointers and smart pointers. See the test for examples.
I also removed some unnecessary `inline` keywords when I was touching functions.
> Give the cfg_node iterators for outedges and inedges

- jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.cpp
- jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.hpp
- jlm/hls/backend/rvsdg2rhls/add-prints.cpp
- jlm/hls/backend/rvsdg2rhls/alloca-conv.cpp
- jlm/hls/backend/rvsdg2rhls/instrument-ref.cpp
- jlm/hls/backend/rvsdg2rhls/mem-conv.cpp
- jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.cpp
- jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.hpp
- jlm/llvm/backend/jlm2llvm/instruction.cpp
- jlm/llvm/frontend/LlvmInstructionConversion.cpp
- jlm/llvm/ir/operators/IntegerOperations.cpp
- jlm/llvm/ir/operators/IntegerOperations.hpp
- tests/jlm/llvm/backend/llvm/jlm-llvm/test-bitconstant.cpp
- tests/jlm/llvm/frontend/llvm/LlvmPhiConversionTests.cpp
This PR replaces the old bitstring constant operation with a new LLVM specific integer constant operation.
> Add LLVM-specific integer constant operation

- .github/workflows/hls.yml
I am not entirely sure why, but the HLS workflow on #803 fails when it tries to write a comment about changed cycle count.
This has never been an issue before, but it might be because the creator of the PR, or the last committer, is @halvorlinder who has fewer permissions.
I am hoping this change might help with this, but the permission documentation is not very clear
> Give the hls workflow permission to comment on the PR

- .github/workflows/hls.yml
It turns out that specifying permissions directly did not help.
The `GITHUB_TOKEN` created for a `pull_request` workflow only has permissions inside the source repository. Since @halvorlinder's PR #803 is from his own fork, the workflow can not comment on the PR in this repository.
I found one workaround on [stack overflow](https://stackoverflow.com/a/71683208) that uploads the comment as an artifact, and uses a second workflow triggered by the completion of the first workflow to comment.
However, for an informative comment like this, I think it makes more sense to just allow the commenting to fail silently.
> Allow the HLS cycle count changed comment on PRs to fail

- jlm/llvm/backend/RvsdgToIpGraphConverter.cpp
- tests/jlm/llvm/backend/RvsdgToIpGraphConverterTests.cpp
When handling an empty gamma node with 2 subregions, then the RvsdgToIpGraphConverter can create select operations instead of basic blocks. However, the operands of the select operations were switched. This PR fixes this problem.
Close #836
Close #586
> Fix operand order in select creation in RvsdgToIpGraphConverter

- jlm/llvm/backend/RvsdgToIpGraphConverter.cpp
- tests/jlm/llvm/backend/RvsdgToIpGraphConverterTests.cpp
The RvsdgToIpGraphConverter was not handling the conversion of empty gamma nodes with match nodes to select operations correctly. This PR fixes the problems with it by creating select predicate operations in case there is no identity mapping in the match operation.
Close #846
> Fix select creation in RvsdgToIpGraphConverter

- jlm/llvm/opt/alias-analyses/RegionAwareModRefSummarizer.cpp
- jlm/llvm/opt/alias-analyses/RegionAwareModRefSummarizer.hpp
The last PR removed LoadVolatileNodes, but forgot to change some lines in the RegionAwareModRefSummarizer. This should fix this problem.
> Fix bug in RegionAwareModRefSummarizer [AndersenRegionAware]

- jlm/hls/backend/firrtl2verilog/FirrtlToVerilogConverter.cpp
> Keep names when generating Verilog

- jlm/llvm/backend/dot/DotWriter.cpp
- jlm/mlir/backend/JlmToMlirConverter.cpp
- jlm/rvsdg/Makefile.sub
- jlm/rvsdg/UnitType.cpp
- jlm/rvsdg/UnitType.hpp
Introduce the UnitType to allow representing a type that holds no data (akin to the C "void" type). This can formally be used in places where "something" must be produced, but it has no content -- this will later be used in pattern matching over types without a content in generalized gamma constructs.
Prepare places that currently balk on existency of this type so its usage can be introduced without breakage later.
> Introduce UnitType

- jlm/hls/backend/rvsdg2rhls/distribute-constants.cpp
- jlm/hls/backend/rvsdg2rhls/mem-sep.cpp
- jlm/hls/backend/rvsdg2rhls/merge-gamma.cpp
- jlm/hls/opt/cne.cpp
- jlm/llvm/frontend/InterProceduralGraphConversion.cpp
- jlm/llvm/ir/CallSummary.cpp
- jlm/llvm/ir/operators/call.cpp
- jlm/llvm/opt/DeadNodeElimination.cpp
- jlm/llvm/opt/cne.cpp
- jlm/llvm/opt/pull.cpp
- jlm/mlir/backend/JlmToMlirConverter.cpp
- jlm/rvsdg/gamma.cpp
- jlm/rvsdg/gamma.hpp
- tests/jlm/llvm/backend/dot/DotWriterTests.cpp
- tests/jlm/llvm/opt/TestDeadNodeElimination.cpp
Add an argument to gamma branch subregions that represents the "content" of the discriminator object that gamma is matching over. For booleans/control decisions, they do not have a content (although one could argue that they carry an "assertion" that a certain proposition holds that in turn some operations in the contained region may be dependent on -- e.g. a divisor not being zero, a pointer being non-null etc.) -- so use UnitType here by default.
This allows Gamma to serve as general pattern matching operator which makes the contents of e.g. an algebraic type being matched over available in its sub branches.
Adapt all places using Gamma API to deal with the fact that there is another argument now not corresponding to any EntryVar.
> GammaNode: Add pattern matching support to gamma

- jlm/hls/backend/rvsdg2rhls/GammaConversion.cpp
- jlm/hls/backend/rvsdg2rhls/decouple-mem-state.cpp
- jlm/hls/backend/rvsdg2rhls/hls-function-util.hpp
- jlm/hls/backend/rvsdg2rhls/mem-queue.cpp
- jlm/hls/ir/hls.cpp
- jlm/hls/ir/hls.hpp
- jlm/hls/opt/InvariantLambdaMemoryStateRemoval.cpp
- jlm/hls/opt/cne.cpp
- jlm/llvm/opt/InvariantValueRedirection.cpp
- jlm/llvm/opt/alias-analyses/PointsToGraph.hpp
- jlm/llvm/opt/alias-analyses/TopDownModRefEliminator.cpp
- jlm/llvm/opt/cne.cpp
- jlm/llvm/opt/inversion.cpp
- jlm/llvm/opt/push.cpp
- jlm/llvm/opt/reduction.cpp
- jlm/llvm/opt/unroll.cpp
- jlm/rvsdg/view.cpp
- tests/jlm/hls/backend/rvsdg2rhls/MemoryConverterTests.cpp
- tests/jlm/hls/backend/rvsdg2rhls/TestFork.cpp
- tests/jlm/hls/opt/InvariantLambdaMemoryStateRemovalTests.cpp
- tests/jlm/llvm/opt/test-inversion.cpp
- tests/jlm/llvm/opt/test-push.cpp
- tests/jlm/llvm/opt/test-unroll.cpp
- tests/jlm/mlir/frontend/TestMlirToJlmConverter.cpp
- tests/jlm/rvsdg/test-gamma.cpp
Ensure to consistently match on node type instead of operation for all structural nodes. This is a necessary prerequisite for reworking operations eventually.
> Match on node type for structural nodes

- jlm/hls/backend/rvsdg2rhls/decouple-mem-state.cpp
- jlm/hls/backend/rvsdg2rhls/hls-function-util.hpp
- jlm/llvm/ir/operators/Load.cpp
- jlm/rvsdg/simple-node.hpp
A lot of transformation in the code simply have to check whether the owners of inputs/outputs are SimpleNode of a specific operation type. Those methods simplify these checks.
> Add TryGetSimpleNodeAndOp() methods

- jlm/llvm/opt/InvariantValueRedirection.cpp
- tests/jlm/llvm/opt/InvariantValueRedirectionTests.cpp
The pass falsely assumed that if the CallMemoryStateExitSplit node is present for a call, then all the other memory state nodes (i.e., CallMemoryStateEntryMerge,  LambdaMemoryStateEntrySplit, LambdaMemoryStateExitMerge) are present as well. This does not have to be the case in general. For example, it might be that after region-aware state encoding, the LambdaMemoryStateEntrySplit node is missing, while all other nodes are present.
Close #937
> Fix bug in InvariantValueRedirection pass

- jlm/util/Math.hpp
- tests/jlm/util/TestMath.cpp
These are both used by the type size code used by the LocalAliasAnalysis
> Add RoundUpToMultipleOf and RoundUpToPowerOf2 to Math.hpp

- jlm/hls/backend/rvsdg2rhls/UnusedStateRemoval.cpp
- jlm/hls/backend/rvsdg2rhls/decouple-mem-state.cpp
On my system these files do not compile, despite CI passing fine. I assume Ubuntu has slightly different headers causing the added headers to already be transitively included.
> Fix includes of standard library headers

- jlm/llvm/ir/types.cpp
- jlm/llvm/ir/types.hpp
- tests/jlm/llvm/ir/TestTypes.cpp
The logic surrounding alignment was based on opening up Compiler Explorer and testing with `sizeof()` and `alignof()`
> Add functions for getting size and alignment of types

- tests/jlm/llvm/ir/operators/MemoryStateOperationTests.cpp
I assume this was added by CLion accidentally. It does not do anything, and causes compilation to fail when not on Ubuntu
> Remove weird and unused llvm include

- jlm/llvm/ir/operators/Load.hpp
- jlm/llvm/ir/operators/MemoryStateOperations.cpp
- jlm/llvm/ir/operators/MemoryStateOperations.hpp
- jlm/llvm/ir/operators/Store.hpp
- jlm/llvm/opt/reduction.cpp
- jlm/llvm/opt/reduction.hpp
- tests/jlm/llvm/ir/operators/MemoryStateOperationTests.cpp
Adds three LambdaExitMemoryStateMergeOperation normalizations that together render load, store, and alloca operations independent from the lambda node, leading to them potentially becoming dead code. This should be able to remove a significant amount of load, stores, and allocas that are normally eliminated by mem2reg.
> Add LambdaExitMemoryStateMergeOperation normalizations

- jlm/mlir/backend/JlmToMlirConverter.cpp
The gamma did not include the argument for the region select input. This inconsistency caused a bug in the llvm-to-mlir-to-llvm conversion.
> Updated handling of gamma arguments in MLIR

- jlm/hls/backend/rvsdg2rhls/merge-gamma.cpp
- jlm/hls/backend/rvsdg2rhls/rvsdg2rhls.cpp
Contrary to what the comment in the code says, DNE is perfectly capable to remove the dead gammas created by the merge gamma pass.
> Simplify HLS merge gamma pass

- jlm/rvsdg/Makefile.sub
- jlm/rvsdg/node.cpp
- jlm/rvsdg/node.hpp
- tests/jlm/rvsdg/InputTests.cpp
The GetOwner() method of the Input class allows us to compute the next input directly in the iterator, simplifying all the iterator code a lot.
> Overhaul Input::iterator class

- tests/jlm/rvsdg/test-nodes.cpp
My local compiler things this leads to a dangling pointer. Avoid the problem by removing `const`
> Avoid compilation error

- jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.cpp
- jlm/hls/backend/rhls2firrtl/RhlsToFirrtlConverter.hpp
- jlm/hls/backend/rvsdg2rhls/distribute-constants.cpp
- jlm/hls/backend/rvsdg2rhls/hls-function-util.cpp
- jlm/hls/backend/rvsdg2rhls/mem-conv.cpp
- jlm/hls/backend/rvsdg2rhls/mem-queue.cpp
- jlm/hls/backend/rvsdg2rhls/merge-gamma.cpp
- jlm/hls/util/view.cpp
- jlm/llvm/opt/DeadNodeElimination.cpp
We would like to remove the SimpleOutput subclass, but before we can do
this we need to refactor all the dispatching that is based on it.
> Refactor SimpleOutput dispatching

- tests/jlm/rvsdg/test-nodes.cpp
PR #1097 invalidated the NodeInputConstIteration unit test by removing the const from the node. Fix this as well as unifying the NodeInputIteration and NodeInputConstIteration unit test.
> Fix NodeInputIteration tests

- jlm/rvsdg/graph.cpp
- jlm/rvsdg/graph.hpp
- jlm/rvsdg/region.cpp
- jlm/rvsdg/region.hpp
- jlm/rvsdg/tracker.cpp
- jlm/rvsdg/tracker.hpp
- jlm/rvsdg/traverser.cpp
- jlm/rvsdg/traverser.hpp
- tests/jlm/rvsdg/test-bottomup.cpp
- tests/jlm/rvsdg/test-topdown.cpp
Replaces the global tracker registry with a per-region registry as trackers work nowadays solely on a per-region basis and not on a per-graph basis any longer.
> Remove global tracker registry

- jlm/mlir/frontend/MlirToJlmConverter.cpp
- jlm/mlir/frontend/MlirToJlmConverter.hpp
The ConvertOp() function used to return the node instead of the outputs of the created node.
> ConvertOp() now returns the created node's outputs

- jlm/llvm/opt/DeadNodeElimination.cpp
- jlm/llvm/opt/alias-analyses/TopDownModRefEliminator.cpp
- jlm/rvsdg/MatchType.hpp
Select by node type, rather than operation type, in three places that presently dispatch on the wrong criterion.
> Clean up two places: Dispatch based on node type, not operation type

- jlm/llvm/ir/operators/MemoryStateOperations.cpp
- jlm/llvm/ir/operators/MemoryStateOperations.hpp
- tests/jlm/llvm/ir/operators/MemoryStateOperationTests.cpp
Adjusts the LambdaExitMemoryStateMergeOperation normalizations to correctly handle memory node identifiers.
> Fix LambdaExitMemoryStateMergeOperation normalizations

- jlm/mlir/frontend/MlirToJlmConverter.cpp
- jlm/mlir/frontend/MlirToJlmConverter.hpp
The MLIR frontend was creating unique_ptr when converting types. This has now been changed to shared_ptr<const rvsdg::Type>.
> Changed to using shared_ptr for types

- tests/Makefile.sub
The change makes it possible to pass in an alternative for compiling the tests by providing JLC= to the 'make check' target. This makes is possible to use the ./scripts/jlc-mlir-roundtrip.py to test the MLIR frontend and backend.
> Enable specifying JLC for 'make check'

- jlm/llvm/Makefile.sub
- jlm/llvm/ir/attribute.hpp
- jlm/llvm/opt/alias-analyses/AliasAnalysis.cpp
- jlm/llvm/opt/alias-analyses/AliasAnalysis.hpp
- jlm/llvm/opt/alias-analyses/LocalAliasAnalysis.cpp
- jlm/llvm/opt/alias-analyses/PointsToGraphAliasAnalysis.cpp
- jlm/llvm/opt/alias-analyses/PointsToGraphAliasAnalysis.hpp
- jlm/rvsdg/control.hpp
- tests/jlm/llvm/opt/alias-analyses/PointsToGraphAliasAnalysisTests.cpp
It also includes the `ChainedAliasAnalysis` because it is a very small class.
I also had to add some `#includes` to make things compile on my machine after a system update.
`TryGetConstantSignedInteger` is moved to `AliasAnalysis.{cpp,hpp}` because it is needed by both analyses, but ideally it should live somewhere even more general. It uses `NormalizeOutputs` however, which should also be moved somewhere more general.
> Add PointsToGraphAliasAnalysis and tests

- jlm/llvm/ir/operators/Load.cpp
- tests/jlm/llvm/ir/operators/LoadTests.cpp
This PR overhauls the LoadLoadState normalization and utilizes a MemoryStateJoinOperation in it, instead of a MemoryStateMergeOperation.
> Overhaul LoadLoadState normalization

- jlm/mlir/backend/JlmToMlirConverter.cpp
- jlm/mlir/frontend/MlirToJlmConverter.cpp
- jlm/tooling/Makefile.sub
- tests/jlm/mlir/TestJlmToMlirToJlm.cpp
- tools/Makefile.sub
- tools/jhls/Makefile.sub
We have previously linked together tests and tools (`jlm-opt`, `jlc`) with `libllvm.a` in front of `libmlir.a`.
This has for some reason worked perfectly fine before, and I have no idea why it suddenly stopped working, as the conversions I added are pretty much identical to existing conversions, and your class looks just like other operations.
However, I got a lot of "undefined reference to typeinfo for FMulAddIntrinsicOperation", "undefined reference to vtable for FMulAddIntrinsicOperation"
To appease the linker, I had to place the dependency (`libllvm.a`) after the dependant (`libmlir.a`). This is something I have previously had to do with `-l` libraries, but apparently it can also be necessary for regular input files... I wish I understood better. Do you know anything about this …
> Add conversions of FMulAddIntrinsicOp to/from MLIR

- jlm/hls/backend/rvsdg2rhls/add-buffers.cpp
- jlm/hls/backend/rvsdg2rhls/check-rhls.cpp
- jlm/hls/backend/rvsdg2rhls/decouple-mem-state.cpp
- jlm/hls/backend/rvsdg2rhls/mem-conv.cpp
- jlm/hls/backend/rvsdg2rhls/mem-queue.cpp
- jlm/hls/backend/rvsdg2rhls/merge-gamma.cpp
- jlm/hls/backend/rvsdg2rhls/remove-redundant-buf.cpp
- jlm/hls/backend/rvsdg2rhls/rhls-dne.cpp
- jlm/llvm/ir/operators/Load.cpp
- jlm/llvm/ir/operators/MemoryStateOperations.cpp
- jlm/llvm/ir/operators/Store.cpp
- jlm/llvm/ir/operators/operators.cpp
- jlm/llvm/ir/operators/sext.cpp
- jlm/llvm/opt/alias-analyses/LocalAliasAnalysis.cpp
- jlm/rvsdg/bitstring/bitoperation-classes.cpp
- jlm/rvsdg/control.cpp
- jlm/rvsdg/node.hpp
- tests/jlm/hls/backend/rvsdg2rhls/DistributeConstantsTests.cpp
- tests/jlm/hls/backend/rvsdg2rhls/MemoryStateSplitConversionTests.cpp
- tests/jlm/hls/backend/rvsdg2rhls/SinkInsertionTests.cpp
- tests/jlm/hls/backend/rvsdg2rhls/TestTheta.cpp
As talked about previously, many calls to `TryGetSimpleNodeAndOptionalOp` were only used to check the type of the operation. This function does it directly.
I searched for all `TryGetSimpleNodeAndOptionalOp` and replaced when applicable
> Add IsOwnerNodeOperation and make use of it

- jlm/llvm/ir/operators/Load.cpp
- tests/jlm/llvm/ir/operators/LoadTests.cpp
Extends the NormalizeIOBarrierAlloocaAddress normalization to trace the input address of the IOBarrier through gamma and theta nodes.
> Extend LoadNonVolatileOperation::NormalizeIOBarrierAllocaAddress()

- jlm/llvm/ir/operators/Store.cpp
- tests/jlm/llvm/ir/operators/StoreTests.cpp
Extends the NormalizeIOBarrierAlloocaAddress normalization to trace the input address of the IOBarrier through gamma and theta nodes.
> Extend StoreNonVolatileOperation::NormalizeIOBarrierAllocaAddress()

- jlm/hls/backend/rvsdg2rhls/UnusedStateRemoval.cpp
- tests/jlm/hls/backend/rvsdg2rhls/UnusedStateRemovalTests.cpp
The removal of pass-through loop variables in the UnusedStateRemoval pass was simply broken. It removed happily loop variables even if they were not just simple pass-through. If a loop variables post value operand was simply another loop variables pre operand, then the loop variables were already removed. This is simply wrong. The unit test exemplifies this with loop variable Y and Z, which take each others value.
This PR solves an issue that arose in PR #1242
> HLS: Fix pass-through loop variable removal in UnusedStateRemoval pass
